### ISSUE TITLE
PEPPER-DeepVariant   error

### ISSUE THREAD

**Issue by MichelMoser** [kishwarshafin/pepper#11]
Hi @kishwarshafin, 

I would like to run PEPPER-DeepVariant to call structural variants on a polished nanopore assembly of ours and compare against other SV callers. 
Unfortunately, the run ends with repetitive `TypeError: merge_overlaps() got an unexpected keyword argument 'strict'`

Could be a problem with samtools option settings or some IO issue?

I am using the container with version: 
` singularity run --nv pepper_latest.sif  pepper --version
PEPPER VERSION:  0.0.6
`

Files, which got created were `PEPPER_SNP_OUPUT.vcf.gz  PEPPER_SNP_OUPUT.vcf.gz.tbi  whatshap_intermediate_outputs_vcf
`

Full log is attached. 

[SV_PEPPER-17367768_4294967294.log](https://github.com/kishwarshafin/pepper/files/5160707/SV_PEPPER-17367768_4294967294.log)

Thank you, 
Michel

```
I0819 01:00:13.015127 140071232530176 make_examples.py:390] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0819 01:00:13.021996 140455424919296 make_examples.py:390] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0819 01:00:13.069498 139737563899648 genomics_reader.py:223] Reading /net/cn-1/mnt/SCRATCH/michelmo/Projects/Bos/Bos_all_flye27_20K/Bos_allF27_20K.remap.bam with NativeSamReader
W0819 01:00:13.069753 139737563899648 make_examples.py:581] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.
I0819 01:00:13.091958 139737563899648 make_examples.py:537] Task 23/32: Preparing inputs
I0819 01:00:13.152297 139737563899648 genomics_reader.py:223] Reading /net/cn-1/mnt/SCRATCH/michelmo/Projects/Bos/Bos_all_flye27_20K/Bos_allF27_20K.remap.bam with NativeSamReader
I0819 01:00:13.520422 139737563899648 make_examples.py:537] Task 23/32: Common contigs are ['contig_100', 'contig_1005', 'contig_1006', 'contig_1017', 'contig_1024', 'contig_1025', 'contig_1032', 'contig_1036' .....
.....'scaffold_841', 'scaffold_910', 'scaffold_978']
Traceback (most recent call last):
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1666, in <module>
    app.run(main)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1656, in main
    make_examples_runner(options)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1514, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1417, in processing_regions_from_options
    options.exclude_calling_regions)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 749, in build_calling_regions
    regions = ranges.RangeSet.from_contigs(contigs)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 168, in from_contigs
    contigs)
  File "/work/users/Bazel.runfiles_mfwlrdfe/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 125, in __init__
    tree.merge_overlaps(strict=False)
TypeError: merge_overlaps() got an unexpected keyword argument 'strict'
I0819 01:00:13.074622 140314582742784 genomics_reader.py:223] Reading /net/cn-1/mnt/SCRATCH/michelmo/Projects/Bos/Bos_all_flye27_20K/Bos_allF27_20K.remap.bam with NativeSamReader
W0819 01:00:13.074861 140314582742784 make_examples.py:581] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.

```

**Comment by MichelMoser** [comment]
probably related with:  https://github.com/google/deepvariant/issues/255

**Comment by kishwarshafin** [comment]
Hi @MichelMoser ,

PEPPER-DeepVariant pipeline is designed to work with GRCh38 as the reference and can only call small variants. Structural variant calling is a slightly different problem and we are not pursuing that right now. With this pipeline, you can only call variants that are <=50bp against GRCh38. We need some development time to make the pipeline work with de novo assemblies.

If you are trying to get SV calls, I'd recommend [Sniffles](https://github.com/fritzsedlazeck/Sniffles). 

Thanks for trying out the pipeline!
