### ISSUE TITLE
stitching issue

### ISSUE THREAD

**Issue by MichelMoser** [kishwarshafin/pepper#13]
Dear @kishwarshafin , 

I run into a stitching error when polishing a genome of 2.6 Gb. 

```
ESC[0mESC[93mINFO: PROCESSING CONTIG: Merge_1247393
ESC[0mESC[94mINFO: FINISHED PROCESSING Merge_1247393, POLISHED SEQUENCE LENGTH: 1242063.
ESC[0mESC[93mINFO: PROCESSING CONTIG: Merge_1249877
ESC[0mESC[94mINFO: FINISHED PROCESSING Merge_1249877, POLISHED SEQUENCE LENGTH: 1167455.
ESC[0mESC[93mINFO: PROCESSING CONTIG: Merge_1331364
ESC[0mESC[94mINFO: FINISHED PROCESSING Merge_1331364, POLISHED SEQUENCE LENGTH: 1301381.
ESC[0mESC[93mINFO: PROCESSING CONTIG: Merge_1331809
ESC[0mESC[94mINFO: FINISHED PROCESSING Merge_1331809, POLISHED SEQUENCE LENGTH: 1267766.
ESC[0mESC[93mINFO: PROCESSING CONTIG: Merge_1377874
ESC[0mESC[94mINFO: FINISHED PROCESSING Merge_1377874, POLISHED SEQUENCE LENGTH: 1359750.
ESC[0mESC[93mINFO: PROCESSING CONTIG: Merge_14585707_0-9923020
ESC[0mTraceback (most recent call last):
  File "/opt/conda/bin/pepper", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/pepper/pepper.py", line 373, in main
    FLAGS.threads_per_caller)
  File "/opt/conda/lib/python3.7/site-packages/pepper/modules/python/polish.py", line 119, in polish
    threads)
  File "/opt/conda/lib/python3.7/site-packages/pepper/modules/python/perform_stitch.py", line 68, in perform_stitch
    threads)
  File "/opt/conda/lib/python3.7/site-packages/pepper/modules/python/StitchV2.py", line 217, in create_consensus_sequence
    contig, st, end = sequence_chunk_key.split('-')
ValueError: too many values to unpack (expected 3)
Sun Sep 20 08:04:50 CEST 2020
runtime 37683

```

Command used: 
```
singularity run --nv /net/cn-1/mnt/SCRATCH/michelmo/Projects/CONTAINERS/pepper_latest.sif  pepper polish \
--bam $BAM \
--fasta $ASSEMBLY \
--model_path /net/cn-1/mnt/SCRATCH/michelmo/Projects/CONTAINERS/pepper_models/pepper_r941_guppy305_human.pkl \
--output_file Simon_Sept2020_ALL_pepper \
--threads 64 \
--batch_size 512 \
--gpu \
--num_workers 8
```

Let me know if i should add the full log. 

Is it possible to rerun only stitching step, as hdf file got created successfully?

Thanks, 
Michel

**Comment by kishwarshafin** [comment]
Ah, this is a legacy bug imported from HELEN. I'll fix this soon and notify you here. 

Yes, you can run stitch without having to run the previous steps.

**Comment by MichelMoser** [comment]
ok great, thank you!

**Comment by kishwarshafin** [comment]
@MichelMoser ,

I have merged a new branch that fixes your issue. Can you please do these:
```bash
cd /path/to/pepper/
git pull origin master
make clean
make install
. ./venv/bin/activate

pepper stitch \
-i <Simon_Sept2020_ALL_pepper/predictions_xxx> \
--bam $BAM \
--fasta $ASSEMBLY \
--model_path /net/cn-1/mnt/SCRATCH/michelmo/Projects/CONTAINERS/pepper_models/pepper_r941_guppy305_human.pkl \
--output_file Simon_Sept2020_ALL_pepper \
--threads 64 \
--batch_size 512 \
--gpu \
--num_workers 8
```

This should complete the stitch step.

**Comment by MichelMoser** [comment]
Thank you @kishwarshafin, works fine!
