### ISSUE TITLE
Specific chromosome run

### ISSUE THREAD

**Issue by tahashmi** [kishwarshafin/pepper#130]
Dear Kishwar,

I am wondering how to run PEPPER variant calling on a `BAM` file with only focusing for a specific chromosome like `chr20`? Thanks.

**Comment by kishwarshafin** [comment]
@tahashmi , you can use `-r chr20` which will run the pipeline only on `chr20`.

**Comment by tahashmi** [comment]
Thanks.

**Comment by tahashmi** [comment]
Can you please check the log to see what's going wrong, actually this [use case](https://github.com/kishwarshafin/pepper/blob/r0.7/docs/pipeline_singularity/HiFi_variant_calling_singularity.md) was working fine yesterday but today I have deleted root .singularity dir to make some space and downloaded `.sif` files again. 
```
[02-01-2022 20:23:46] INFO: VARIANT CALLING MODULE SELECTED
[02-01-2022 20:23:46] INFO: [1/8] RUNNING THE FOLLOWING COMMAND
-------
mkdir -p /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output;
mkdir -p /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/logs;
mkdir -p /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/intermediate_files;
cp /opt/pepper_models/PEPPER_VARIANT_HIFI_V6.pkl /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/intermediate_files/
-------
[02-01-2022 20:23:47] INFO: [2/8] RUNNING THE FOLLOWING COMMAND
-------
time pepper_variant call_variant -b /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/HG003.GRCh38.chr20.pFDA_truthv2.bam -f /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/GRCh38_no_alt.chr20.fa -t 64 -m /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/intermediate_files/PEPPER_VARIANT_HIFI_V6.pkl -o /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/ -s Sample --hifi 2>&1 | tee /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/logs/1_pepper.log
-------
[02-01-2022 20:23:51] INFO: HiFi VARIANT CALLING MODE SELECTED.
[02-01-2022 20:23:51] INFO: THRESHOLDS ARE SET TO:
[02-01-2022 20:23:51] INFO: MIN MAPQ:                           5
[02-01-2022 20:23:51] INFO: MIN SNP BASEQ:                      10
[02-01-2022 20:23:51] INFO: MIN INDEL BASEQ:                    10
[02-01-2022 20:23:51] INFO: MIN SNP FREQUENCY:                  0.1
[02-01-2022 20:23:51] INFO: MIN INSERT FREQUENCY:               0.12
[02-01-2022 20:23:51] INFO: MIN DELETE FREQUENCY:               0.12
[02-01-2022 20:23:51] INFO: MIN COVERAGE THRESHOLD:             2
[02-01-2022 20:23:51] INFO: MIN CANDIDATE SUPPORT:              2
[02-01-2022 20:23:51] INFO: MIN SNP CANDIDATE FREQUENCY:        0.1
[02-01-2022 20:23:51] INFO: MIN INDEL CANDIDATE FREQUENCY:      0.12
[02-01-2022 20:23:51] INFO: SKIP INDEL CANDIDATES:              False
[02-01-2022 20:23:51] INFO: MAX ALLOWED CANDIDATE IN ONE SITE:  4
[02-01-2022 20:23:51] INFO: MIN SNP PREDICTIVE VALUE:           0.1
[02-01-2022 20:23:51] INFO: MIN INSERT PREDICTIVE VALUE:        0.001
[02-01-2022 20:23:51] INFO: MIN DELETE PREDICTIVE VALUE:        0.1
[02-01-2022 20:23:51] INFO: SNP QV CUTOFF FOR RE-GENOTYPING:    20
[02-01-2022 20:23:51] INFO: INDEL QV CUTOFF FOR RE-GENOTYPING:  20
[02-01-2022 20:23:51] INFO: CALL VARIANT MODULE SELECTED
[02-01-2022 20:23:51] INFO: RUN-ID: 02012022_202351
[02-01-2022 20:23:51] INFO: IMAGE OUTPUT: /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/images_02012022_202351/
[02-01-2022 20:23:51] INFO: STEP 1/3 GENERATING IMAGES:
[02-01-2022 20:23:51] INFO: COMMON CONTIGS FOUND: ['chr20']
[02-01-2022 20:23:51] INFO: TOTAL CONTIGS: 1 TOTAL INTERVALS: 645 TOTAL BASES: 64444166
[02-01-2022 20:23:51] INFO: STARTING PROCESS: 0 FOR 11 INTERVALS
[02-01-2022 20:23:54] INFO: [THREAD 00] 10/11 COMPLETE (90%) [ELAPSED TIME: 0 Min 2 Sec]
[02-01-2022 20:23:54] INFO: THREAD 0 FINISHED SUCCESSFULLY.
[02-01-2022 20:23:56] INFO: FINISHED IMAGE GENERATION
[02-01-2022 20:23:56] INFO: TOTAL ELAPSED TIME FOR GENERATING IMAGES: 0 Min 4 Sec
[02-01-2022 20:23:56] INFO: STEP 2/3 RUNNING INFERENCE
[02-01-2022 20:23:56] INFO: OUTPUT: /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/predictions_02012022_202351/
[02-01-2022 20:23:56] INFO: DISTRIBUTED CPU SETUP.
[02-01-2022 20:23:56] INFO: TOTAL CALLERS: 64
[02-01-2022 20:23:56] INFO: THREADS PER CALLER: 1
[02-01-2022 20:23:56] INFO: MODEL LOADING TO ONNX
[02-01-2022 20:23:56] INFO: SAVING MODEL TO ONNX
/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset9.py:2095: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  warnings.warn("Exporting a model to ONNX with a batch_size other than 1, " +
[02-01-2022 20:23:57] INFO: MODEL QUANTIZATION ENABLED.
[02-01-2022 20:23:57] INFO: QUANTIZED MODEL SAVED.
[02-01-2022 20:23:58] INFO: SETTING THREADS TO: 1.
[02-01-2022 20:23:59] INFO: STARTING INFERENCE.
[02-01-2022 20:24:01] INFO: THREAD 0 FINISHED SUCCESSFULLY.
[02-01-2022 20:24:08] INFO: FINISHED PREDICTION
[02-01-2022 20:24:08] INFO: ELAPSED TIME: 0 Min 10 Sec
[02-01-2022 20:24:08] INFO: PREDICTION FINISHED SUCCESSFULLY.
[02-01-2022 20:24:08] INFO: TOTAL ELAPSED TIME FOR INFERENCE: 0 Min 11 Sec
[02-01-2022 20:24:08] INFO: STEP 3/3 FINDING CANDIDATES
[02-01-2022 20:24:08] INFO: OUTPUT: /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/
[02-01-2022 20:24:08] INFO: STARTING CANDIDATE FINDING.
[02-01-2022 20:24:09] INFO: FINISHED PROCESSING, TOTAL CANDIDATES FOUND: 0
[02-01-2022 20:24:09] INFO: FINISHED PROCESSING, TOTAL VARIANTS IN PEPPER: 0
[02-01-2022 20:24:09] INFO: FINISHED PROCESSING, TOTAL VARIANTS SELECTED FOR RE-GENOTYPING: 0
[02-01-2022 20:24:09] INFO: TOTAL TIME SPENT ON CANDIDATE FINDING: 0 Min 1 Sec
[02-01-2022 20:24:09] INFO: TOTAL ELAPSED TIME FOR FINDING CANDIDATES: 0 Min 17 Sec

real    0m22.857s
user    7m32.713s
sys     0m38.497s
[02-01-2022 20:24:09] INFO: [3/8] RUNNING THE FOLLOWING COMMAND
-------
mv /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/PEPPER_VARIANT_FULL.vcf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/;
mv /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/PEPPER_VARIANT_OUTPUT_PEPPER.vcf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/;
mv /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/PEPPER_VARIANT_OUTPUT_VARIANT_CALLING.vcf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/;
bgzip /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_FULL.vcf;
tabix -p vcf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_FULL.vcf.gz;
bgzip /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_OUTPUT_PEPPER.vcf;
tabix -p vcf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_OUTPUT_PEPPER.vcf.gz;
bgzip /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_OUTPUT_VARIANT_CALLING.vcf;
tabix -p vcf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_OUTPUT_VARIANT_CALLING.vcf.gz;
rm -rf /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/pepper/;
echo "CONTIGS FOUND IN PEPPER VCF:";
zcat /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_FULL.vcf.gz | grep -v '#' | cut -f1 | uniq
-------
CONTIGS FOUND IN PEPPER VCF:
[02-01-2022 20:24:10] INFO: [4/8] RUNNING THE FOLLOWING COMMAND
-------
time margin phase /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/HG003.GRCh38.chr20.pFDA_truthv2.bam /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/GRCh38_no_alt.chr20.fa /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_FULL.vcf.gz /opt/margin_dir/params/phase/allParams.haplotag.pb-hifi.json -t 64 -V -o /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PHASED.PEPPER_MARGIN 2>&1 | tee /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/logs/2_margin_haplotag.log;
samtools index -@64 /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PHASED.PEPPER_MARGIN.haplotagged.bam
-------
Running OpenMP with 64 threads.
> Parsing model parameters from file: /opt/margin_dir/params/phase/allParams.haplotag.pb-hifi.json
> Parsed 0 total VCF entries from /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_FULL.vcf.gz; kept 0 HETs, skipped 0 for region, 0 for not being PASS, 0 for being homozygous, 0 for being INDEL
No valid VCF entries found!
[E::hts_open_format] Failed to open file "/gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PHASED.PEPPER_MARGIN.haplotagged.bam" : No such file or directory
samtools index: failed to open "/gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PHASED.PEPPER_MARGIN.haplotagged.bam": No such file or directory
[02-01-2022 20:24:10] ERROR: None]
[02-01-2022 20:24:10] THE FOLLOWING COMMAND FAILED: time margin phase /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/HG003.GRCh38.chr20.pFDA_truthv2.bam /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/GRCh38_no_alt.chr20.fa /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PEPPER_VARIANT_FULL.vcf.gz /opt/margin_dir/params/phase/allParams.haplotag.pb-hifi.json -t 64 -V -o /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PHASED.PEPPER_MARGIN 2>&1 | tee /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/logs/2_margin_haplotag.log;
samtools index -@64 /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/output/PHASED.PEPPER_MARGIN.haplotagged.bam]
```

[2_margin_haplotag.log](https://github.com/kishwarshafin/pepper/files/7981454/2_margin_haplotag.log)
[1_pepper.log](https://github.com/kishwarshafin/pepper/files/7981455/1_pepper.log)

**Comment by kishwarshafin** [comment]
@tahashmi ,

Can you please re-download the BAM file and make sure it has the reads by doing a `samtools stats`. It looks like PEPPER didn't find any reads that align to `chr20`.

**Comment by tahashmi** [comment]
These are the statistics. Strange!
```
# This file was produced by samtools stats (1.13-46-ga9ff2a2+htslib-1.13-43-gb136e5d) and can be plotted using plot-bamstats
# This file contains statistics for all reads.
# The command line was:  stats /gpfs/home3/tahmad/tahmad/testing/pacbio_dv/hifi-case-study/input/data/HG003.GRCh38.chr20.pFDA_truthv2.bam
# CHK, Checksum [2]Read Names   [3]Sequences    [4]Qualities
# CHK, CRC32 of reads which passed filtering followed by addition (32bit overflow)
CHK     67fdcfcc        3dc6a875        258950f8
# Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN      raw total sequences:    158889  # excluding supplementary and secondary reads
SN      filtered sequences:     0
SN      sequences:      158889
SN      is sorted:      1
SN      1st fragments:  158889
SN      last fragments: 0
SN      reads mapped:   158889
SN      reads mapped and paired:        0       # paired-end technology bit set + both mates mapped
SN      reads unmapped: 0
SN      reads properly paired:  0       # proper-pair bit set
SN      reads paired:   0       # paired-end technology bit set
SN      reads duplicated:       0       # PCR or optical duplicate bit set
SN      reads MQ0:      65      # mapped and MQ=0
SN      reads QC failed:        0
SN      non-primary alignments: 0
SN      supplementary alignments:       7955
SN      total length:   2318502357      # ignores clipping
SN      total first fragment length:    2318502357      # ignores clipping
SN      total last fragment length:     0       # ignores clipping
SN      bases mapped:   2318502357      # ignores clipping
SN      bases mapped (cigar):   2308094291      # more accurate
SN      bases trimmed:  0
SN      bases duplicated:       0
SN      mismatches:     0       # from NM fields
SN      error rate:     0.000000e+00    # mismatches / bases mapped (cigar)
SN      average length: 14591
SN      average first fragment length:  14592
SN      average last fragment length:   0
SN      maximum length: 31276
SN      maximum first fragment length:  31276
SN      maximum last fragment length:   0
SN      average quality:        81.9
SN      insert size average:    0.0
SN      insert size standard deviation: 0.0
SN      inward oriented pairs:  0
SN      outward oriented pairs: 0
SN      pairs with other orientation:   0
SN      pairs on different chromosomes: 0
SN      percentage of properly paired reads (%):        0.0
# First Fragment Qualities. Use `grep ^FFQ | cut -f 2-` to extract this part.
# Columns correspond to qualities and rows to cycles. First column is the cycle number.
...
...
...
```

**Comment by kishwarshafin** [comment]
@tahashmi , Can you please post the command that you are running? Something is corrupted.

**Comment by tahashmi** [comment]
I am using this command:
```
#!/bin/bash
#SBATCH -N 1
#SBATCH --exclusive
#SBATCH -t 8:0:0
#SBATCH -p thin
#SBATCH --output=pepper.out

BASE="${PWD}/hifi-case-study"

rm -r "${BASE}/output"
# Set up input data
INPUT_DIR="${BASE}/input/data"
REF="GRCh38_no_alt.chr20.fa"
BAM="HG003.GRCh38.chr20.pFDA_truthv2.bam"
OUTPUT_VCF="PEPPER_MARGIN_DEEPVARIANT_OUTPUT.vcf.gz"

# Set the number of CPUs to use
THREADS="64"

# Set up output directory
OUTPUT_DIR="${BASE}/output"

## Create local directory structure
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"
mkdir -p input

# Download the data to input directory
wget -P ${INPUT_DIR} https://downloads.pacbcloud.com/public/dataset/HG003/deepvariant-case-study/HG003.GRCh38.chr20.pFDA_truthv2.bam
wget -P ${INPUT_DIR} https://downloads.pacbcloud.com/public/dataset/HG003/deepvariant-case-study/HG003.GRCh38.chr20.pFDA_truthv2.bam.bai
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/usecase_data/GRCh38_no_alt.chr20.fa
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/usecase_data/GRCh38_no_alt.chr20.fa.fai

## Pull the docker image to sigularity, this is a 6.6GB download
#cd /scratch-shared/tahmad/images
#singularity pull docker://kishwars/pepper_deepvariant:r0.6

#cd ..

# Run PEPPER-Margin-DeepVariant
singularity exec --bind /usr/lib/locale/ \
/scratch-shared/tahmad/images/pepper_deepvariant_r0.6.sif \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}" \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-t ${THREADS} \
--hifi
```

I suspect there might be some issue on the HPC storage `/home` dir for reading operation. 

I am getting some weird issue for DeepVariant as well.

```
 12:58:25.999722 22476620805952 make_examples_core.py:239] Task 8/128: Overhead for preparing inputs: 0 seconds
2022-02-01 12:58:26.166144: W ./third_party/nucleus/util/proto_clif_converter.h:75] Failed to cast type N6google8protobuf14DynamicMessageE
Traceback (most recent call last):
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 180, in <module>
    app.run(main)
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 170, in main
    make_examples_core.make_examples_runner(options)
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1667, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 965, in process
    reads = self.region_reads(
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1049, in region_reads
    reads.extend(sam_reader.query(region))
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/scratch-local/tahmad.407824/Bazel.runfiles_jwp7f_x9/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /scratch-shared/tahmad/bio_data/long/tests/reference/GRCh38_no_alt_analysis_set.fasta --reads /scratch-shared/tahmad/bio_data/long/tests/input/HG003.GRCh38.chr20.pFDA_truthv2.bam --examples /scratch-local/tahmad.407824/tmpo55a6jpu/make_examples.tfrecord@128.gz --add_hp_channel --alt_aligned_pileup diff_channels --noparse_sam_aux_fields --pileup_image_width 199 --norealign_reads --regions chr20 --nosort_by_haplotypes --vsc_min_fraction_indels 0.12 --task 8
``` 

I will check with them and let you know. Thanks.

**Comment by kishwarshafin** [comment]
@tahashmi , you should also switch to `r0.7` which is the latest version.

**Comment by renzhiyang** [comment]
> 

@tahashmi I had the same issue as you while running on HPC. Could you tell me how to deal with this problem? Thank you in advance.

**Comment by tahashmi** [comment]
@renzhiyang I didn't resolve this issue yet. I think there is some TensorFlow version issue in DeepVariant-2.0.0 and above with TensorFlow installed on our HPC. PEPPER-r0.4 is working fine with  DeepVariant-1.0.0.

**Comment by renzhiyang** [comment]
Hi @tahashmi, thank you so much for your reply. I will have a try on PEPPER-r0.4.
