### ISSUE TITLE
undefined symbol: libdeflate_free_compressor

### ISSUE THREAD

**Issue by liuzhen51032** [kishwarshafin/pepper#153]
Hi，
 The following error occurred while running this software：

  (pepper) root@bio-ngs-1-at:/Apps/pepper# pepper_variant -h
Traceback (most recent call last):
  File "/Apps/pepper/venv/bin/pepper_variant", line 11, in <module>
    load_entry_point('pepper-polish==0.8.0', 'console_scripts', 'pepper_variant')()
  File "/Apps/pepper/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Apps/pepper/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Apps/pepper/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Apps/pepper/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Apps/pepper/venv/lib/python3.8/site-packages/pepper_polish-0.8.0-py3.8-linux-x86_64.egg/pepper_variant/pepper_variant.py", line 11, in <module>
    from pepper_variant.modules.python.ImageGenerationUI import ImageGenerationUtils
  File "/Apps/pepper/venv/lib/python3.8/site-packages/pepper_polish-0.8.0-py3.8-linux-x86_64.egg/pepper_variant/modules/python/ImageGenerationUI.py", line 10, in <module>
    from pepper_variant.build import PEPPER_VARIANT
ImportError: /Apps/pepper/venv/lib/python3.8/site-packages/pepper_polish-0.8.0-py3.8-linux-x86_64.egg/pepper_variant/build/PEPPER_VARIANT.cpython-38-x86_64-linux-gnu.so: undefined symbol: libdeflate_free_compressor

No error message during installation，
OS：Ubuntu 20.4 LST
Thanks！

**Comment by kishwarshafin** [comment]
@liuzhen51032 , I think this is coming from htslib, are you able to independently install htslib successfully on your system?

**Comment by liuzhen51032** [comment]
@kishwarshafin Thanks for your reply,hstlib is already installed on the system,and reinstalled it，But the problem was not solved。

***@nj-bio-ngs-1-at:/Apps/pepper$ bgzip --version
bgzip (htslib) 1.15.1-40-g226c1a8
Copyright (C) 2022 Genome Research Ltd.

**Comment by kishwarshafin** [comment]
hi @liuzhen51032 ,

Sorry for dropping the ball on this. However, did you make sure to install all required libraries as suggested:

```
sudo apt-get -y install cmake make git gcc g++ autoconf bzip2 lzma-dev zlib1g-dev \
libcurl4-openssl-dev libpthread-stubs0-dev libbz2-dev \
liblzma-dev libhdf5-dev python3-pip python3-virtualenv virtualenv
```
