### ISSUE TITLE
Error installing via pip

### ISSUE THREAD

**Issue by kushalsuryamohan** [kishwarshafin/pepper#16]
Hello,
I am having issues installing pepper via pip on an HPC platform running CentOS 7.7.
Note that I do not have admin privileges.

This is the installation command I run
```(my_root) suryamok@nl001:~/GenomeAssemblyPipeline % python3 -m pip install --user pepper-polish ```

While it downloads all the requisite files, it is killed at the last step - 

```Collecting pepper-polish
  Using cached https://files.pythonhosted.org/packages/91/ed/1044b74956faf3fda73bffaa8223e5d40a549fc360799128fb6ecc9c8428/pepper_polish-0.1.1.tar.gz
Collecting h5py==2.10.0 (from pepper-polish)
  Using cached https://files.pythonhosted.org/packages/3f/c0/abde58b837e066bca19a3f7332d9d0493521d7dd6b48248451a9e3fe2214/h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting tqdm==4.38.0 (from pepper-polish)
  Using cached https://files.pythonhosted.org/packages/b9/08/8505f192efc72bfafec79655e1d8351d219e2b80b0dec4ae71f50934c17a/tqdm-4.38.0-py2.py3-none-any.whl
Collecting numpy==1.16.6 (from pepper-polish)
  Using cached https://files.pythonhosted.org/packages/17/06/337132f52ae41fca603473f44f4ea100eb030e096da0ea38563a74f63872/numpy-1.16.6-cp37-cp37m-manylinux1_x86_64.whl
Collecting wget==3.2 (from pepper-polish)
  Using cached https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
Collecting torch==1.4.0 (from pepper-polish)
  Downloading https://files.pythonhosted.org/packages/1a/3b/fa92ece1e58a6a48ec598bab327f39d69808133e5b2fb33002ca754e381e/torch-1.4.0-cp37-cp37m-manylinux1_x86_64.whl (753.4MB)
    99% |████████████████████████████████| 753.4MB 27.7MB/s eta 0:00:01Killed
```

I would appreciate your help in looking into this.

P.S - I tried installing from source but I think I am missing virtualenv

```
(my_root) suryamok@nl001:~/GenomeAssemblyPipeline/pepper % make install
test -d venv || virtualenv venv --python=python3 --prompt "(pepper) "
Running virtualenv with interpreter /gstore/apps/Python/3.7.3-GCCcore-6.3.0-bare/bin/python3
/gstore/apps/Python/3.7.3-GCCcore-6.3.0-bare/bin/python3: can't find '__main__' module in '/gstore/apps/Python/3.7.3-GCCcore-6.3.0-bare/lib/python3.7/site-packages/virtualenv-16.6.1-py3.7.egg'
make: *** [Makefile:5: venv/bin/activate] Error 1
```

**Comment by kishwarshafin** [comment]
@kushalsuryamohan:
```bash
Downloading https://files.pythonhosted.org/packages/1a/3b/fa92ece1e58a6a48ec598bab327f39d69808133e5b2fb33002ca754e381e/torch-1.4.0-cp37-cp37m-manylinux1_x86_64.whl (753.4MB)
    99% |████████████████████████████████| 753.4MB 27.7MB/s eta 0:00:01Killed
```
This usually happens when you run out of memory. Which is very unlikely given that you are just installing the packages. Can you please let me know how much RAM you have in your machine?

**Comment by kishwarshafin** [comment]
To locally install virtualenv without root permission and install PEPPER:

```bash
git clone https://github.com/kishwarshafin/pepper.git
cd pepper
python3 -m pip install virtualenv --user
python3 -m virtualenv venv --python=python3 --prompt "(pepper) "
source ./venv/bin/activate
python3 setup.py install
pepper --help
```

**Comment by kushalsuryamohan** [comment]
Thanks, @kishwarshafin, 
I was able to install (I think) virtualenv. However, I get the following error when I try to install pepper -

```
(pepper) suryamok@nl002:~/pepper % python3 setup.py install 
running install
running bdist_egg
running egg_info
creating pepper_polish.egg-info
writing pepper_polish.egg-info/PKG-INFO
writing dependency_links to pepper_polish.egg-info/dependency_links.txt
writing entry points to pepper_polish.egg-info/entry_points.txt
writing requirements to pepper_polish.egg-info/requires.txt
writing top-level names to pepper_polish.egg-info/top_level.txt
writing manifest file 'pepper_polish.egg-info/SOURCES.txt'
package init file 'pepper_snp/modules/python/helper/__init__.py' not found (or not a regular file)
package init file 'pepper_hp/__init__.py' not found (or not a regular file)
package init file 'pepper_hp/modules/python/__init__.py' not found (or not a regular file)
package init file 'pepper_hp/modules/python/models/__init__.py' not found (or not a regular file)
reading manifest file 'pepper_polish.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'build.sh'
writing manifest file 'pepper_polish.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
CMAKE VERSION:  3.17.3
---------- Running CMake prepare ----------------------------------------
CMake Error at /gstore/apps/CMake/3.17.3-GCCcore-6.3.0/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "3")
Call Stack (most recent call first):
  /gstore/apps/CMake/3.17.3-GCCcore-6.3.0/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /gstore/apps/CMake/3.17.3-GCCcore-6.3.0/share/cmake-3.17/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:12 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/gstore/home/suryamok/pepper/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    zip_safe=False,
  File "/gstore/home/suryamok/pepper/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/gstore/home/suryamok/pepper/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/gstore/home/suryamok/pepper/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/gstore/home/suryamok/pepper/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/gstore/home/suryamok/pepper/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/gstore/home/suryamok/pepper/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 62, in run
    cwd=self.build_temp, env=env)
  File "/gstore/apps/Anaconda3/5.0.1/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/gstore/home/suryamok/pepper', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/gstore/home/suryamok/pepper/build/temp.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/gstore/home/suryamok/pepper/venv/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
(pepper) suryamok@nl002:~/pepper % 
```

Appreciate your help.

In terms of RAM, I am trying to install in my local directory on a SLURM HPC. Should I not do this from a login node? I can start an interactive session and try to install if that's the issue. Let me know.

Thanks!

**Comment by kishwarshafin** [comment]
@kushalsuryamohan,

Looks like you are missing python3-dev:
```bash
Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
```

Looks like the node is not configured correctly for python and are missing `python3-dev` installation. Usually with anaconda they come by default. How do you usually run other programs? Would a `docker` help you in this case?

Also, if the login node has limited memory then you can't install this module in there.

**Comment by kushalsuryamohan** [comment]
Hi @kishwarshafin, I was able to resolve the installation crash by requesting an interactive session and installing pepper.
Naive question here but I assume one can simply replace the marginPolish-HELEN pipeline using the One step polishing (in my case the CPU machine use case) workflow after aligning long reads to the draft genome?

Thanks again for your prompt responses!

**Comment by kishwarshafin** [comment]
Hi @kushalsuryamohan ,

Thank you, it's very good to know that you were able to solve this issue. If you have any suggestion about what would've made your installation easier, please let me know. 

To answer your query, yes, we developed `PEPPER` to replace `MarginPolish-HELEN`. The workflow is: `Generate an assembly` > `Align reads back to the assembly` > `run PEPPER` > `get polished assembly`. I strongly recommend to not use `racon` or any other polisher before `PEPPER`. We often see polishers like `Medaka` over-polish and destroys the initial assembly integrity. Although aligning reads back to the assembly and then polishing it is still not the best answer, but, this is the best solution we have got so far.

**Comment by kushalsuryamohan** [comment]
Hi @kishwarshafin, interesting observation about RACON. 
I currently have an assembly that's generated using the following workflow:
1) Generate long-read draft assembly (Canu)
2) Polish genome using Illumina data from same animal (PILON) - Typically, I've polished 4-5x to improve base call error rates
3) Hi-C for scaffolding.

However, when annotating the genome, I still find regions of the genome that were not fixed using Illumina data alone and this is not good for gene finding (especially since base call errors could lead to erroneous stop codons inside genes). 
So, I was planning on using the assembly from (3) as the reference to work through the PEPPER pipeline.
Please advice if this is suitable. Much appreciated.

**Comment by kishwarshafin** [comment]
Hi @kushalsuryamohan ,

There's a section on how Illumina-based polishing doesn't work very good right out of the box in this paper (https://www.nature.com/articles/s41587-020-0503-6)

This table:
![image](https://user-images.githubusercontent.com/10559039/96658872-86587480-12fa-11eb-9bbb-76da85ef37c5.png)

Shows that polishing the raw assembly usually don't improve the assembly quality that much.

This is my suggestion:
1. Align ONT reads to Canu assembly and run PEPPER.
2. Take PEPPER polished assembly, align Illumina reads and polish with PILON (1x)
3. Take pilon polished assembly and scaffold with Hi-C, this will give you the final assembly

This should give you a good quality assembly.

**Comment by kishwarshafin** [comment]
@kushalsuryamohan I'm going to close this issue. Please feel free to open the issue if you have any other questions.

**Comment by kushalsuryamohan** [comment]
Hello again @kishwarshafin ,
I set up a polishing run on SLURM and am facing a samtools error (not quite sure why this is the case).
Here is my script:

```
minimap2 -ax map-ont -t 64 ${GENOME} ONT.fastq.gz | samtools view -hb -q 60 -F 0x904 > unsorted.bam ; samtools sort -@ 32 unsorted.bam | samtools view > reads_2_assembly.0x904q60.bam

samtools index -@32 reads_2_assembly.0x904q60.bam

#Step 2
pepper polish \
                --bam reads_2_assembly.bam \
                --fasta ${GENOME} \
                --model_path ./models/PEPPER_polish_haploid_guppy360.pkl \
                --output_file ./pepper_polished \
                --threads 64 \
                --batch_size 128
```

The last few lines of the log for this is as follows:
```
[M::worker_pipeline::3765.882*6.01] mapped 85430 sequences
[M::worker_pipeline::3903.785*6.02] mapped 83474 sequences
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 4262179
[main_samview] truncated file.
[bam_sort_core] merging from 32 files and 32 in-memory blocks...
samtools index: "reads_2_assembly.0x904q60.bam" is in a format that cannot be usefully indexed
[10-21-2020 17:02:04]  INFO: POLISH MODULE SELECTED
[10-21-2020 17:02:04] ERROR: CAN NOT LOCATE BAM FILE.
slurmstepd: error: Detected 1 oom-kill event(s) in step 33109180.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

Can you please help troubleshoot? 
The oom error is preceded by samtools so I think they're linked?
My samtools version is 1.10 (from htslib 1.10).

Thanks,
Kushal

**Comment by kishwarshafin** [comment]
Hi @kushalsuryamohan ,

I think your bam files name is `reads_2_assembly.0x904q60.bam` and you've set `reads_2_assembly.bam` as PEPPER's input?

**Comment by kishwarshafin** [comment]
Hi @kushalsuryamohan ,

```bash
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 4262179
```

This means your fastq is corrupted? Can you run it through some QC pipeline to be sure you are using a valid fastq?

**Comment by kushalsuryamohan** [comment]
Hi @kishwarshafin I could successfully align the reads to the genome but I get the following error when attempting to index the bam file. 

```
[bam_sort_core] merging from 144 files and 12 in-memory blocks...
samtools index: "reads_2_assembly.0x904q60.bam" is in a format that cannot be usefully indexed
INVALID BAM INDEX FILE. PLEASE CHECK IF FILE IS INDEXED: reads_2_assembly.0x904q60.bam
```
Is there a reason this could be occurring?

Thanks,
Kushal

**Comment by kushalsuryamohan** [comment]
Just FYI:

```
suryamok@nl003:~/GenomeAssemblyResults/PolishedGenomes_after_Pepper % ls -lrt /scratch/u/suryamok/temp/

-rw-r--r-- 1 suryamok dnaseq 187005256844 Oct 22 17:13 reads_2_assembly.sam
-rw-r--r-- 1 suryamok dnaseq  66267423275 Oct 23 17:31 unsorted.bam
```

These are the first few lines of the bam file ''reads_2_assembly.0x904q60.bam"
```
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 1
[main_samview] truncated file.
```

The sam file looks to be okay - first few lines including header : 
```
@SQ     SN:Scaffold_1;HRSCAF=2  LN:19368
@SQ     SN:Scaffold_2;HRSCAF=3  LN:72781
@SQ     SN:Scaffold_3;HRSCAF=5  LN:19088
@SQ     SN:Scaffold_4;HRSCAF=6  LN:48658
@SQ     SN:Scaffold_5;HRSCAF=7  LN:64774
@SQ     SN:Scaffold_6;HRSCAF=8  LN:50361
@SQ     SN:Scaffold_7;HRSCAF=9  LN:45777
@SQ     SN:Scaffold_8;HRSCAF=10 LN:46464
@SQ     SN:Scaffold_9;HRSCAF=11 LN:42339
....

@PG     ID:minimap2     PN:minimap2     VN:2.17-r941    CL:minimap2 -ax map-ont -t 24 animal_tIq1P.fasta R5283.fastq.gz R5284.fastq.gz R5295.fastq.gz R5296.fastq.gz
f025d5f6-12ac-4e60-8eb3-0a90b95c0b3f    4       *       0       0       *       *       0       0       TTGATCGGACCC    ""$""$'#""""    rl:i:0
23318678-752d-4744-b699-0d2af8cfe800    4       *       0       0       *       *       0       0       CGTGGATCGGACCC  """"$""#'$""#"  rl:i:0
9693650b-11d6-4515-a541-cbe63848daf8    4       *       0       0       *       *       0       0       CGTGGATCGAT     """"$"##"""     rl:i:0
cb20e2f4-8274-4e24-99fc-a47782aa8f46    4       *       0       0       *       *       0       0       ATATTCTGGCGGGCGCGCCGGGATGGATG   &%"%"""""""""""""""#$
($$%%""#   rl:i:0
f00be4d6-b1c6-4e03-b38e-d6c74e59f2ad    4       *       0       0       *       *       0       0       AACGT   """""   rl:i:0
8623ce49-b07f-492a-b0c5-ec4fb97f0f35    4       *       0       0       *       *       0       0       CGTGGACGCGGTTCC """""""#"##"$$" rl:i:0
a97babce-7e32-44f3-b032-8f6f40d5f271    4       *       0       0       *       *       0       0       GGCGTGCGATCGGATCGGTCC   """""""""##$%"#"%$#$"   rl:i:
0
0ccce88d-f0c3-4945-89fb-b4f5e37a1a99    4       *       0       0       *       *       0       0       ATGGT   """""   rl:i:0
c8f4a3e1-0601-4d8e-ba6f-b3a5611a87c7    4       *       0       0       *       *       0       0       ATCAATTGTACTTCGTTCCGGTGCATATTGCTCCAGTGCATGAAATAAGATGC
TCTCTCTTTTGCTTGAGACGGGTTCTGCTACATTTCCCAAAAAGTCCCTTACTATAAGGTTTGGCAGGACACGATCCTTGGCATAGATATATATATCAATTGTGATATTCCTCATGATATCCACATGTAACATCAGATATAAAATAAAGGTCCATTG
CAAACTTTTTTGTCTACCTGCATAGCTTTATTTGCAAGAATATAAATCTCTCTTGTTTTAAAGTAGGAGCCCCATTTACAAAAAGCAGGTTTGTCAATATCCTGTTAGTATATATAACTGAATTATTAAAATGAGCAACATGGCAACATTTAGAAAA
GATGGGACTTTATATAGTACATTCATATAATTCTAGTGTTTCAGCACTAAACTGCAGTGTATTTCAACGGGTTTGGTGCCATCTGACTCTCAGACTGACACTGGGCAACTCTCAAAATAAAATTTACTACAAAACAAACAAACAAATAAAACATGCA
GTAATGTAGTCAGACAACCTTATCAGCACAGAAAAATATCTCTTTTACCCTCTAATGGTGGTCCTGAGGACCTTCTTCCCAATGTCTGGAAGAACAGCGGAGTCTTTCTTGAAGTATCAAGGAAGAATTTGTCTAAGAGACGATTTGATTCCAGGAT
AAATTTTAAAAATTTGTTTTTATCTTTTAATAATTTATTCATAATAAACATTTCCTTTCAATTTTTTAAAAATATTCGTAGGCATCAATATAGATGGGAAGAAGAGGTTAAGTATTAGTCGTGTTATGACATGATAGTGAAATGATCTAAACTATAT
AGGTTTGTAGTTATTCACATAATTTGTATGGATCTCTGTCTCTCATCTTCTTTCTTTCTTTCTTTCTTT     (/&)&)'(((,-*&&07+.)264.+.$.*)--.-''.),()''1.)+.+-++(+,-,,%*,,+#"$%&$'&0&3)1.*$#$##
%&-:0-7/-984+),-,)*('&')11.)()5,)%#$%&.+$%&&)(,-1.214555:996..,-.0/(',3)--156-9-1*1-/-00447+''++289:75872-636339;3458,.0.+((-4-6671-/9<:7**0/.-185350.'#&'1/&
%0*#%%)"&&(,136,*,544'*7('894,-'#$"2(%)/3+*'-2.-12;93*'()203:<(,-26323:98549/,,-.21'(&%$#"(*+2,/90;:<34,*)',/6)6'&/////<8+(.51'%(+)792138012.)("$#%%,1-'%%#,-
446."((#*0/0)(*()&()++,6;3/3)%%(3+2.(+$(,.::0622.,'/-)**$$&*+,-165654/+*)-/./*155267;8-,046/281+/.-0+51(.-('*1851/8++9<<;:8:2:4+0+()%'#%*,-(/-.$7,260/.+))*,,
++4:;714)'&$'&%"$(-*(*,(&('*,-+*4+'%"%"##"#)$**/+))(.24699-8,-8:7--1+)&'))*87*+)'%%##&*)-+.-/4),/)-3+/25(++./1035165,,.87#%$.-58-++42*07:62066'*3981/8.3;;,,.
43,-.**340+*-3-0:62-185,4+97,*82;;<90345.&'(//./2*1101;;-6*'#)(,.(2(-(&)-%#*--;6500)*''$**#-(33"$"*'&&&&''%&$(%'%"-+,/-*'#(*,+,("(.87+-.+04/180,,+$'5+;7-3,((
*)*0++0534*,+2//,(+&+38*2:8(-80+/:-(,-%     rl:i:35
```

**Comment by kishwarshafin** [comment]
Hi @kushalsuryamohan ,

can you please do the alignment step by step to see what exactly is going on. It would be like this:

```bash
minimap2 -ax map-ont -t 64 ${GENOME} ONT.fastq.gz | samtools view -hb -q 60 -F 0x904 > unsorted.bam 
samtools sort -@32 -o reads_2_assembly.0x904q60.bam unsorted.bam
samtools index -@32 reads_2_assembly.0x904q60.bam
```
Run each command one after another to see exactly what is going wrong.

**Comment by kushalsuryamohan** [comment]
Working on this - will update as soon as I have results.

**Comment by kushalsuryamohan** [comment]
Hi @kishwarshafin , looks like running the jobs sequentially (and on a high mem node) seems to have done the trick.
Pepper is now running. First few lines of the log here:

```
[11-02-2020 14:44:30]  INFO: POLISH MODULE SELECTED
[11-02-2020 14:44:30] INFO: RUN-ID: 11022020_144430
[11-02-2020 14:44:30] INFO: IMAGE OUTPUT: /home/pepper_polished/images_11022020_144430/
[11-02-2020 14:44:30] STEP 1: GENERATING IMAGES
```
Will update this once the run is finished (or if there are errors).
Thanks!

**Comment by kishwarshafin** [comment]
thank you for the update @kushalsuryamohan.
