### ISSUE TITLE
bonito v0.3 model doesn't work

### ISSUE THREAD

**Issue by biorover** [kishwarshafin/pepper#25]
Hello, I get the following error when running pepper with your bonito V3 model:

[12-14-2020 10:56:43] STEP 2: RUNNING INFERENCE
[12-14-2020 10:56:43] INFO: PREDICTION OUTPUT: pepperTry2/predictions_12142020_105643/
[12-14-2020 10:56:43] INFO: DISTRIBUTED CPU SETUP
[12-14-2020 10:56:43] INFO: SETUP:
[12-14-2020 10:56:43] INFO: TOTAL CALLERS: 10
[12-14-2020 10:56:43] INFO: THREADS PER CALLER: 1
[12-14-2020 10:56:43] INFO: DATA-LOADER PER CALLER: 10
Traceback (most recent call last):
  File "/home/jessica/tools/pepper/venv/bin/pepper", line 33, in <module>
    sys.exit(load_entry_point('pepper-polish==0.1.5', 'console_scripts', 'pepper')())
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/pepper_polish-0.1.5-py3.6-linux-x86_64.egg/pepper/pepper.py", line 327, in main
    FLAGS.num_workers)
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/pepper_polish-0.1.5-py3.6-linux-x86_64.egg/pepper/modules/python/polish.py", line 110, in polish
    threads)
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/pepper_polish-0.1.5-py3.6-linux-x86_64.egg/pepper/modules/python/call_consensus.py", line 160, in call_consensus
    threads)
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/pepper_polish-0.1.5-py3.6-linux-x86_64.egg/pepper/modules/python/call_consensus.py", line 57, in polish_cpu
    num_workers)
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/pepper_polish-0.1.5-py3.6-linux-x86_64.egg/pepper/modules/python/models/predict_distributed_cpu.py", line 127, in predict_cpu
    num_classes=ImageSizeOptions.TOTAL_LABELS)
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/pepper_polish-0.1.5-py3.6-linux-x86_64.egg/pepper/modules/python/models/ModelHander.py", line 89, in load_simple_model_for_training
    checkpoint = torch.load(model_path, map_location='cpu')
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/jessica/tools/pepper/venv/lib/python3.6/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

This happens regardless of the pepper version (tried 0.0.6 and 0.1.5) or install method (docker, pip, and from source). The models that download with "pepper download_models", in contrast, work fine.

**Comment by kishwarshafin** [comment]
@biorover ,

It looks like the model you downloaded got corrupted during download and `PEPPER` can't open the model correctly. Can you please download the model the following way and try the command again:

```bash
wget https://storage.googleapis.com/kishwar-helen/models_pepper/PEPPER_POLISH_R941_BONITO_V0.3_MICROBIAL.pkl
```

**Comment by kishwarshafin** [comment]
@biorover , I'm closing this issue, for now, please feel free to re-open if the issue has not been fixed.
