### ISSUE TITLE
ONNX error while running the test data from quickstart

### ISSUE THREAD

**Issue by yingchen69** [kishwarshafin/pepper#28]
Hi,

I tried to run cpu version of PEPPER-DeepVariant pipeline with the test data using singularity 3.5.3. But I ran into error with ONNX. 

Here is the log:

[12-23-2020 01:10:51] INFO: CALL VARIANT MODULE SELECTED
[12-23-2020 01:10:51] INFO: RUN-ID: 12232020_011051
[12-23-2020 01:10:51] INFO: IMAGE OUTPUT: /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD3/output/pepper_snp/imag
es_12232020_011051/
[12-23-2020 01:10:51] STEP 1: GENERATING IMAGES
[12-23-2020 01:10:51] INFO: TOTAL CONTIGS: 1 TOTAL INTERVALS: 2
[12-23-2020 01:10:51] STARTING THREAD: 0 FOR 1 INTERVALS
[12-23-2020 01:10:52] THREAD 0 FINISHED SUCCESSFULLY.
[12-23-2020 01:10:52] FINISHED IMAGE GENERATION
[12-23-2020 01:10:52] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 0 Min 0 Sec
[12-23-2020 01:10:52] STEP 2: RUNNING INFERENCE
[12-23-2020 01:10:52] INFO: PREDICTION OUTPUT: /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD3/output/pepper_snp
/predictions_12232020_011051/
[12-23-2020 01:10:52] INFO: DISTRIBUTED CPU SETUP.
[12-23-2020 01:10:52] INFO: TOTAL CALLERS: 24
[12-23-2020 01:10:52] INFO: THREADS PER CALLER: 1
[12-23-2020 01:10:52] INFO: MODEL LOADING TO ONNX
[12-23-2020 01:10:52] INFO: SAVING MODEL TO ONNX
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_opset9.py:1436: UserWarning: Exporting a model to ONNX with a batch_
size other than 1, with a variable lenght with GRU can cause an error when running the ONNX model with a different batch size. 
Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 399, in main
    FLAGS.probability_threshold)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 114, in call_variant
    threads)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 161, in run_inference
    output_dir)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 116, in polish_genome_distribut
ed_cpu
    predict_distributed_cpu(image_dir, file_chunks, output_dir, model_path, batch_size, callers, threads_per_caller, num_worker
s)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_cpu.py", line 150, in predi
ct_distributed_cpu
    'output_hidden': {0: 'batch_size'}})
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 436, in _export
    with torch.serialization._open_file_like(f, 'wb') as opened_file:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 30] Read-only file system: '/opt/pepper_models/PEPPER_SNP_R941_guppy360_model.pkl.onnx'

Any suggestion?

Thanks a lot for the help.

Ying

**Comment by kishwarshafin** [comment]
Hi @yingchen69 ,

Can you please paste the command here so I can see if I can try to reproduce the error locally? I think there's a very easy solution to this.

**Comment by yingchen69** [comment]
Hi,

Thanks a lot for the quick response. The command is:

module purge

module load singularity/3.5.3

BASE="/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2"

INPUT_DIR="${BASE}/input/data"
REF="GRCh38_no_alt_chr20.fa"
BAM="HG002_prom_R941_guppy360_2_GRCh38_TEST.bam"
TRUTH_VCF="HG002_GRCh38_GIABv4.1.TRUTH.TEST.vcf.gz"
TRUTH_BED="HG002_GRCh38_GIABv4.1.TRUTH.TEST.bed"

THREADS="24"

OUTPUT_DIR="${BASE}/output"
OUTPUT_VCF="PEPPER_HP_DEEPVARIANT_FINAL_OUTPUT.vcf.gz"

srun singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper_deepvariant_cpu:latest \
/opt/run_pepper_deepvariant.sh \
-f "${INPUT_DIR}/${REF}" \
-b "${INPUT_DIR}/${BAM}" \
-o "${OUTPUT_DIR}" \
-t ${THREADS} \
-r chr20:1000000-1020000 \
-x 1

Thanks,

Ying

**Comment by kishwarshafin** [comment]
@yingchen69 , I was able to reproduce and solve this issue. You need to do two more steps to run this successfully:

Run it like this:
```bash
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/variant_calling_data/pFDA_v2/Nanopore/PEPPER_trained_models/PEPPER_SNP_R941_guppy360_model.pkl
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/variant_calling_data/pFDA_v2/Nanopore/PEPPER_trained_models/PEPPER_HP_R941_guppy360_model.pkl

PEPPER_SNP_MODEL=PEPPER_SNP_R941_guppy360_model.pkl
PEPPER_HP_MODEL=PEPPER_HP_R941_guppy360_model.pkl

singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper_deepvariant_cpu:latest 
/opt/run_pepper_deepvariant.sh 
-f "${INPUT_DIR}/${REF}" 
-b "${INPUT_DIR}/${BAM}" 
-o "${OUTPUT_DIR}" 
-p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" 
-q "${INPUT_DIR}/${PEPPER_HP_MODEL}" 
-t ${THREADS} 
-r chr20:1000000-1020000 
-x 1
```
The error with singularity is that it tried to write onnx file in `/opt/` but failed. I'll make sure the official release supports singularity without any issues. Thank you for reporting this. 

Please let me know if this worked.

**Comment by yingchen69** [comment]
Hi Kishwar,

When I tried to run the above method, I got different errors. The first two are regarding  size mismatch for dense1.weight and dense1.bias:

[12-23-2020 14:08:05] INFO: CALL VARIANT MODULE SELECTED
[12-23-2020 14:08:05] INFO: RUN-ID: 12232020_140805
[12-23-2020 14:08:05] INFO: IMAGE OUTPUT: /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/pepper_snp/images_12232020_140805/
[12-23-2020 14:08:05] STEP 1: GENERATING IMAGES
[12-23-2020 14:08:05] INFO: TOTAL CONTIGS: 1 TOTAL INTERVALS: 2
[12-23-2020 14:08:05] STARTING THREAD: 0 FOR 1 INTERVALS
[12-23-2020 14:08:05] THREAD 0 FINISHED SUCCESSFULLY.
[12-23-2020 14:08:05] FINISHED IMAGE GENERATION
[12-23-2020 14:08:05] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 0 Min 0 Sec
[12-23-2020 14:08:05] STEP 2: RUNNING INFERENCE
[12-23-2020 14:08:05] INFO: PREDICTION OUTPUT: /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/pepper_snp/predictions_12232020_140805/
[12-23-2020 14:08:05] INFO: DISTRIBUTED CPU SETUP.
[12-23-2020 14:08:05] INFO: TOTAL CALLERS: 24
[12-23-2020 14:08:05] INFO: THREADS PER CALLER: 1
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 399, in main
    FLAGS.probability_threshold)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 114, in call_variant
    threads)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 161, in run_inference
    output_dir)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 116, in polish_genome_distributed_cpu
    predict_distributed_cpu(image_dir, file_chunks, output_dir, model_path, batch_size, callers, threads_per_caller, num_workers)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_cpu.py", line 130, in predict_distributed_cpu
    num_classes=ImageSizeOptions.TOTAL_LABELS)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/ModelHander.py", line 109, in load_simple_model_for_training
    transducer_model.load_state_dict(new_model_state_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransducerGRU:
	size mismatch for dense1.weight: copying a param with shape torch.Size([5, 256]) from checkpoint, the shape in current model is torch.Size([15, 256]).
	size mismatch for dense1.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([15]).
mv: cannot stat '/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/pepper_snp/*.vcf': No such file or directory
...

Thanks a lot for the help!

Ying

**Comment by kishwarshafin** [comment]
@yingchen69 , looks like you applid PEPPER HP model for PEPPER SNP. Can you make sure that you see the output right:

```bash
echo "${INPUT_DIR}/${PEPPER_SNP_MODEL}" 
# this should show PEPPER_SNP_R941_guppy360_model.pkl
echo "${INPUT_DIR}/${PEPPER_HP_MODEL}" 
# this should show PEPPER_HP_R941_guppy360_model.pkl

And then you have to make sure your -p and -q parameters are not switched:
-p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" 
-q "${INPUT_DIR}/${PEPPER_HP_MODEL}" 
```

**Comment by yingchen69** [comment]
Hi Kishwar,

I checked and it seems correct.

[yc790@caliburn2 PEPPER-DeepVariant]$ echo "${INPUT_DIR}/${PEPPER_SNP_MODEL}" 
/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/PEPPER_SNP_R941_guppy360_model.pkl
[yc790@caliburn2 PEPPER-DeepVariant]$ echo "${INPUT_DIR}/${PEPPER_HP_MODEL}"
/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/PEPPER_HP_R941_guppy360_model.pkl
[yc790@caliburn2 PEPPER-DeepVariant]$ 

The command is:

singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper_deepvariant_cpu:latest /opt/run_pepper_deepvariant.sh -f "${INPUT_DIR}/${REF}" -b "${INPUT_DIR}/${BAM}" -o "${OUTPUT_DIR}" -p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" -q "${INPUT_DIR}/${PEPPER_HP_MODEL}" -t ${THREADS} -r chr20:1000000-1020000 -x 1

Thanks,

Ying

**Comment by kishwarshafin** [comment]
Can you please try it like this:
```bash
singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper_deepvariant_cpu:latest 
/opt/run_pepper_deepvariant.sh 
-b "${INPUT_DIR}/${BAM}" 
-f "${INPUT_DIR}/${REF}"  
-t ${THREADS}  
-o "${OUTPUT_DIR}" 
-x 1 
-r chr20:1000000-1020000 
-p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" 
-q "${INPUT_DIR}/${PEPPER_HP_MODEL}" 
```

**Comment by yingchen69** [comment]
Hi Kishwar,

I ran the command in your order and got the same error message:

[12-23-2020 22:20:07] INFO: CALL VARIANT MODULE SELECTED
[12-23-2020 22:20:07] INFO: RUN-ID: 12232020_222007
[12-23-2020 22:20:07] INFO: IMAGE OUTPUT: /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/pepper_snp/images_12232020_222007/
[12-23-2020 22:20:07] STEP 1: GENERATING IMAGES
[12-23-2020 22:20:07] INFO: TOTAL CONTIGS: 1 TOTAL INTERVALS: 2
[12-23-2020 22:20:07] STARTING THREAD: 0 FOR 1 INTERVALS
[12-23-2020 22:20:07] THREAD 0 FINISHED SUCCESSFULLY.
[12-23-2020 22:20:07] FINISHED IMAGE GENERATION
[12-23-2020 22:20:07] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 0 Min 0 Sec
[12-23-2020 22:20:07] STEP 2: RUNNING INFERENCE
[12-23-2020 22:20:07] INFO: PREDICTION OUTPUT: /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/pepper_snp/predictions_12232020_222007/
[12-23-2020 22:20:07] INFO: DISTRIBUTED CPU SETUP.
[12-23-2020 22:20:07] INFO: TOTAL CALLERS: 24
[12-23-2020 22:20:07] INFO: THREADS PER CALLER: 1
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 399, in main
    FLAGS.probability_threshold)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 114, in call_variant
    threads)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 161, in run_inference
    output_dir)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 116, in polish_genome_distributed_cpu
    predict_distributed_cpu(image_dir, file_chunks, output_dir, model_path, batch_size, callers, threads_per_caller, num_workers)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_cpu.py", line 130, in predict_distributed_cpu
    num_classes=ImageSizeOptions.TOTAL_LABELS)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/ModelHander.py", line 109, in load_simple_model_for_training
    transducer_model.load_state_dict(new_model_state_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransducerGRU:
	size mismatch for dense1.weight: copying a param with shape torch.Size([5, 256]) from checkpoint, the shape in current model is torch.Size([15, 256]).
	size mismatch for dense1.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([15]).

The command is: singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper_deepvariant_cpu:latest /opt/run_pepper_deepvariant.sh -b "${INPUT_DIR}/${BAM}" -f "${INPUT_DIR}/${REF
}" -t ${THREADS} -o "${OUTPUT_DIR}" -x 1 -r chr20:1000000-1020000 -p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" -q "${INPUT_DIR}/${PEPPER_HP_MODEL}"

Thanks a lot for the help!

Ying

**Comment by kishwarshafin** [comment]
@yingchen69 , I'm not exactly sure what is going on here. I just re-ran everything and it looks right to me:

```bash
singularity --version
# output: 2.5.2-dist

BASE="${HOME}/ont-quickstart"

# Set up input data
INPUT_DIR="${BASE}/input/data"
REF="GRCh38_no_alt_chr20.fa"
BAM="HG002_prom_R941_guppy360_2_GRCh38_TEST.bam"
TRUTH_VCF="HG002_GRCh38_GIABv4.1.TRUTH.TEST.vcf.gz"
TRUTH_BED="HG002_GRCh38_GIABv4.1.TRUTH.TEST.bed"

# Set the number of CPUs to use
THREADS="24"

# Set up output directory
OUTPUT_DIR="${BASE}/output"
OUTPUT_VCF="PEPPER_HP_DEEPVARIANT_FINAL_OUTPUT.vcf.gz"

## Create local directory structure
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"

# Download the data to input directory
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/HG002_prom_R941_guppy360_2_GRCh38_TEST.bam
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/HG002_prom_R941_guppy360_2_GRCh38_TEST.bam.bai
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/GRCh38_no_alt_chr20.fa
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/GRCh38_no_alt_chr20.fa.fai
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/HG002_GRCh38_GIABv4.1.TRUTH.TEST.bed
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/HG002_GRCh38_GIABv4.1.TRUTH.TEST.vcf.gz
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/ont-quickstart/HG002_GRCh38_GIABv4.1.TRUTH.TEST.vcf.gz.tbi

PEPPER_SNP_MODEL=PEPPER_SNP_R941_guppy360_model.pkl
PEPPER_HP_MODEL=PEPPER_HP_R941_guppy360_model.pkl

wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/variant_calling_data/pFDA_v2/Nanopore/PEPPER_trained_models/PEPPER_SNP_R941_guppy360_model.pkl
wget -P ${INPUT_DIR} https://storage.googleapis.com/kishwar-helen/variant_calling_data/pFDA_v2/Nanopore/PEPPER_trained_models/PEPPER_HP_R941_guppy360_model.pkl


singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper_deepvariant_cpu:latest /opt/run_pepper_deepvariant.sh -b "${INPUT_DIR}/${BAM}" -f "${INPUT_DIR}/${REF}" -t ${THREADS} -o "${OUTPUT_DIR}" -x 1 -r chr20:1000000-1020000 -p "${INPUT_DIR}/${PEPPER_SNP_MODEL}" -q "${INPUT_DIR}/${PEPPER_HP_MODEL}"  2>&1 | tee pdv_out.log
```

The output shows:
```bash
NO SAMPLE NAME PROVIDED. USING DEFAULT: SAMPLE
USING DEFAULT DEEPVARIANT_SNP MODEL: R941_guppy360_snp
BAM FILE=/home/kishwar/ont-quickstart/input/data/HG002_prom_R941_guppy360_2_GRCh38_TEST.bam
FASTA FILE=/home/kishwar/ont-quickstart/input/data/GRCh38_no_alt_chr20.fa
PEPPER SNP MODEL=/home/kishwar/ont-quickstart/input/data/PEPPER_SNP_R941_guppy360_model.pkl
PEPPER HP MODEL=/home/kishwar/ont-quickstart/input/data/PEPPER_HP_R941_guppy360_model.pkl
DEEPVARIANT SNP MODEL=/opt/dv_models/R941_guppy360_snp/model.ckpt-23700
DEEPVARIANT HP MODEL=/opt/dv_models/ont-3bams-withHP/model.ckpt-33000
SAMPLE NAME=SAMPLE
REGION=chr20:1000000-1020000
[12-24-2020 04:36:52] INFO: CALL VARIANT MODULE SELECTED
[12-24-2020 04:36:52] INFO: RUN-ID: 12242020_043652
[12-24-2020 04:36:52] INFO: IMAGE OUTPUT: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/
[12-24-2020 04:36:52] STEP 1: GENERATING IMAGES
[12-24-2020 04:36:52] INFO: TOTAL CONTIGS: 1 TOTAL INTERVALS: 2
[12-24-2020 04:36:52] STARTING THREAD: 0 FOR 1 INTERVALS
[12-24-2020 04:36:52] THREAD 0 FINISHED SUCCESSFULLY.
[12-24-2020 04:36:52] FINISHED IMAGE GENERATION
[12-24-2020 04:36:52] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 0 Min 0 Sec
[12-24-2020 04:36:52] STEP 2: RUNNING INFERENCE
[12-24-2020 04:36:52] INFO: PREDICTION OUTPUT: /home/kishwar/ont-quickstart/output/pepper_snp/predictions_12242020_043652/
[12-24-2020 04:36:52] INFO: DISTRIBUTED CPU SETUP.
[12-24-2020 04:36:52] INFO: TOTAL CALLERS: 24
[12-24-2020 04:36:52] INFO: THREADS PER CALLER: 1
[12-24-2020 04:36:52] INFO: MODEL LOADING TO ONNX
[12-24-2020 04:36:52] INFO: SAVING MODEL TO ONNX
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_opset9.py:1436: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable lenght with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  "or define the initial states (h0/c0) as inputs of the model. ")
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_13.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_12.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_2.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_19.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_22.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_10.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_14.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_11.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_21.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_8.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_7.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_16.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_5.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_15.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_20.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_6.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_4.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_3.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_23.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_9.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_17.hdf
WARN: NO IMAGES FOUND IN FILE: /home/kishwar/ont-quickstart/output/pepper_snp/images_12242020_043652/pepper_images_thread_18.hdf
[12-24-2020 04:36:58] INFO: PREDICTION FINISHED SUCCESSFULLY.
[12-24-2020 04:36:58] TOTAL ELAPSED TIME FOR INFERENCE: 0 Min 6 Sec
[12-24-2020 04:36:58] STEP 3: RUNNING STITCH
[12-24-2020 04:36:58] INFO: PREDICTION OUTPUT: /home/kishwar/ont-quickstart/output/pepper_snp/
[12-24-2020 04:36:58] INFO: PROCESSING CONTIG: chr20
[12-24-2020 04:36:59] INFO: FINISHED PROCESSING chr20, TOTAL CANDIDATES FOUND: 55.
[12-24-2020 04:36:59] TOTAL ELAPSED TIME FOR CANDIDATE FINDING: 0 Min 0 Sec
[12-24-2020 04:36:59] TOTAL ELAPSED TIME FOR VARIANT CALLING: 0 Min 7 Sec
I1224 04:36:59.512601 140587393197824 run_deepvariant.py:241] Re-using the directory for intermediate results in /home/kishwar/ont-quickstart/output/dv_intermediate_outputs/
I1224 04:36:59.512936 140587393197824 run_deepvariant.py:251] You set --customized_model. Instead of using the default model for WGS, `call_variants` step will load /opt/dv_models/R941_guppy360_snp/model.ckpt-23700 instead.
```

Can you please paste the first part of the log where the models are set:
```bash
BAM FILE=/home/kishwar/ont-quickstart/input/data/HG002_prom_R941_guppy360_2_GRCh38_TEST.bam
FASTA FILE=/home/kishwar/ont-quickstart/input/data/GRCh38_no_alt_chr20.fa
PEPPER SNP MODEL=/home/kishwar/ont-quickstart/input/data/PEPPER_SNP_R941_guppy360_model.pkl
PEPPER HP MODEL=/home/kishwar/ont-quickstart/input/data/PEPPER_HP_R941_guppy360_model.pkl
DEEPVARIANT SNP MODEL=/opt/dv_models/R941_guppy360_snp/model.ckpt-23700
DEEPVARIANT HP MODEL=/opt/dv_models/ont-3bams-withHP/model.ckpt-33000
```

I'm almost certain that a typo somewhere is causing this.

**Comment by kishwarshafin** [comment]
can you please clear your bash variables and start from scratch?

**Comment by yingchen69** [comment]
Hi Kishwar,

Here is the output log:

NO SAMPLE NAME PROVIDED. USING DEFAULT: SAMPLE
USING DEFAULT DEEPVARIANT_SNP MODEL: R941_guppy360_snp
BAM FILE=/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/HG002_prom_R941_guppy360_2_GRCh38_TEST.bam
FASTA FILE=/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/GRCh38_no_alt_chr20.fa
PEPPER SNP MODEL=/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/PEPPER_SNP_R941_guppy360_model.pkl
PEPPER HP MODEL=/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/PEPPER_HP_R941_guppy360_model.pkl
DEEPVARIANT SNP MODEL=/opt/dv_models/R941_guppy360_snp/model.ckpt-23700
DEEPVARIANT HP MODEL=/opt/dv_models/ont-3bams-withHP/model.ckpt-33000
SAMPLE NAME=SAMPLE
REGION=chr20:1000000-1020000

***** Intermediate results will be written to /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/dv_intermediate_outputs/ in docker. ****


***** Running the command:*****
time seq 0 23 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/GRCh3
8_no_alt_chr20.fa" --reads "/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/HG002_prom_R941_guppy360_2_GRCh38_TEST.bam" --examples "/project1/yc790-001/work/P
EPPER-DeepVariant/ont-quickstart/PD2/output/dv_intermediate_outputs/make_examples.tfrecord@24.gz" --proposed_variants "/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/ou
tput/PEPPER_SNP_OUPUT.vcf.gz" --norealign_reads --variant_caller "vcf_candidate_importer" --task {}

CONTIGS FOUND IN VCF: 

USING HIGH-ACCURACY VARIANT CALLING MODE

***** Intermediate results will be written to /project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/dv_intermediate_outputs/ in docker. ****


***** Running the command:*****
time seq 0 23 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/input/data/GRCh3
8_no_alt_chr20.fa" --reads "/project1/yc790-001/work/PEPPER-DeepVariant/ont-quickstart/PD2/output/WHATSHAP.PHASED.bam" --examples "/project1/yc790-001/work/PEPPER-DeepVariant/ont-quick
start/PD2/output/dv_intermediate_outputs/make_examples.tfrecord@24.gz" --alt_aligned_pileup "diff_channels" --parse_sam_aux_fields --proposed_variants "/project1/yc790-001/work/PEPPER-
DeepVariant/ont-quickstart/PD2/output/PEPPER_HP_OUPUT.vcf.gz" --norealign_reads --sort_by_haplotypes --variant_caller "vcf_candidate_importer" --task {}

Wed Dec 23 22:20:27 EST 2020

Best,

Ying

**Comment by kishwarshafin** [comment]
@yingchen69 looks like it finished successfully?

**Comment by yingchen69** [comment]
Hi Kishwar,

The above log is from the previous failed run :(

I just ran the pipeline again by copying your code in your above thread and it finished successfully. I really do not know what's going on. I tried to find a typo, but could not.

Anyway, thanks a lot for the help!

Happy holidays!

Ying

**Comment by kishwarshafin** [comment]
ok, awesome, thanks for letting me know that it worked. 

Happy holidays!
