### ISSUE TITLE
Problem with Pepper-deepvariant on gpu

### ISSUE THREAD

**Issue by sonaida** [kishwarshafin/pepper#32]
Hi,
I try to run Peeper-deepvariant pipeline in accurate mode with the test data (HG002_prom_R941_guppy360_2_GRCh38_ch20.bam) on gpu (A100, CUDA Version: 11.0).
It is failing with RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED.

Here is my command:
> sudo docker run  --ipc=host \
> --gpus=all \
> -v "${INPUT_DIR}":"${INPUT_DIR}" \
> -v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
> kishwars/pepper_deepvariant_gpu:latest \
> /opt/run_pepper_deepvariant.sh \
> -f "${INPUT_DIR}/${REF}" \
> -b "${INPUT_DIR}/${BAM}" \
> -o "${OUTPUT_DIR}" \
> -t ${THREADS} \
> -x 1

And the log:
```
NO SAMPLE NAME PROVIDED. USING DEFAULT: SAMPLE
USING DEFAULT PEPPER_SNP MODEL: PEPPER_SNP_R941_guppy360_model
USING DEFAULT PEPPER_HP MODEL: PEPPER_HP_R941_guppy360_model
USING DEFAULT DEEPVARIANT_SNP MODEL: R941_guppy360_snp
BAM FILE=/home/dgxuser/ont-case-study/input/data/HG002_prom_R941_guppy360_2_GRCh                                                                                                             38_ch20.bam
FASTA FILE=/home/dgxuser/ont-case-study/input/data/GRCh38_no_alt_chr20.fa
PEPPER SNP MODEL=/opt/pepper_models/PEPPER_SNP_R941_guppy360_model.pkl
PEPPER HP MODEL=/opt/pepper_models/PEPPER_HP_R941_guppy360_model.pkl
DEEPVARIANT SNP MODEL=/opt/dv_models/R941_guppy360_snp/model.ckpt-23700
DEEPVARIANT HP MODEL=/opt/dv_models/ont-3bams-withHP/model.ckpt-33000
SAMPLE NAME=SAMPLE
REGION=
NO REGION PROVIDED. RUNNING ON WHOLE GENOME
[01-21-2021 00:55:41] INFO: CALL VARIANT MODULE SELECTED
[01-21-2021 00:55:41] INFO: RUN-ID: 01212021_005541
[01-21-2021 00:55:41] INFO: IMAGE OUTPUT: /home/dgxuser/ont-case-study/output/pe                                                                                                             pper_snp/images_01212021_005541/
[01-21-2021 00:55:41] STEP 1: GENERATING IMAGES
[01-21-2021 00:55:41] INFO: COMMON CONTIGS FOUND: ['chr20']
[01-21-2021 00:55:41] INFO: TOTAL CONTIGS: 1 TOTAL INTERVALS: 6445
[01-21-2021 00:55:41] STARTING THREAD: 0 FOR 101 INTERVALS
[01-21-2021 00:55:45] INFO:  10/101 COMPLETE (9%) [ELAPSED TIME: 0 Min 3 Sec]
[01-21-2021 00:55:49] INFO:  20/101 COMPLETE (19%) [ELAPSED TIME: 0 Min 7 Sec]
[01-21-2021 00:55:52] INFO:  30/101 COMPLETE (29%) [ELAPSED TIME: 0 Min 10 Sec]
[01-21-2021 00:55:56] INFO:  40/101 COMPLETE (39%) [ELAPSED TIME: 0 Min 14 Sec]
[01-21-2021 00:56:00] INFO:  50/101 COMPLETE (49%) [ELAPSED TIME: 0 Min 18 Sec]
[01-21-2021 00:56:04] INFO:  60/101 COMPLETE (59%) [ELAPSED TIME: 0 Min 22 Sec]
[01-21-2021 00:56:08] INFO:  70/101 COMPLETE (69%) [ELAPSED TIME: 0 Min 26 Sec]
[01-21-2021 00:56:12] INFO:  80/101 COMPLETE (79%) [ELAPSED TIME: 0 Min 30 Sec]
[01-21-2021 00:56:17] INFO:  90/101 COMPLETE (89%) [ELAPSED TIME: 0 Min 35 Sec]
[01-21-2021 00:56:21] INFO:  100/101 COMPLETE (99%) [ELAPSED TIME: 0 Min 39 Sec]
[01-21-2021 00:56:21] THREAD 0 FINISHED SUCCESSFULLY.
[01-21-2021 00:56:27] FINISHED IMAGE GENERATION
[01-21-2021 00:56:27] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 0 Min 45 Sec
[01-21-2021 00:56:27] STEP 2: RUNNING INFERENCE
[01-21-2021 00:56:27] INFO: PREDICTION OUTPUT: /home/dgxuser/ont-case-study/outp                                                                                                             ut/pepper_snp/predictions_01212021_005541/
[01-21-2021 00:56:27] INFO: TOTAL GPU AVAILABLE: 8
[01-21-2021 00:56:27] INFO: AVAILABLE GPU DEVICES: [0, 1, 2, 3, 4, 5, 6, 7]
[01-21-2021 00:56:27] INFO: TOTAL CALLERS: 32
[01-21-2021 00:56:27] INFO: TOTAL THREADS PER CALLER: 2
```
And the traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 399, in main
    FLAGS.probability_threshold)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 114, in call_variant
    threads)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 154, in run_inference
    device_ids)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 87, in polish_genome_distributed_gpu
    predict_distributed_gpu(image_dir, file_chunks, output_dir, model_path, batch_size, total_callers, threads_per_caller, device_ids, num_workers)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 144, in predict_distributed_gpu
    join=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 18 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 122, in setup
    predict(filepath, all_input_files[rank],  output_filepath, model_path, batch_size, num_workers, threads_per_caller, device_ids[rank], rank)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 66, in predict
    output_base, hidden = transducer_model(image_chunk, hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/simple_model.py", line 30, in forward
    x_out, hidden_out = self.gru_encoder(x, hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 716, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

What can be the cause?
Thanks,
Sonya

**Comment by kishwarshafin** [comment]
@sonaida ,

I have not tested the pipeline on a `dgx` box yet. Planning to do it next week. I can help you better in this case. In the mean time, can you please post the output of this:
```bash
docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
```
I wonder if the cuDNN in the docker is too old for your system.

**Comment by sonaida** [comment]
Thank you!

![image](https://user-images.githubusercontent.com/77761689/105336214-076d2380-5bea-11eb-9d80-e509352d1fea.png)

**Comment by kishwarshafin** [comment]
@sonaida ,

I can confirm that there's a CUDNN version mismatch between the docker and the DGx machine as of now. It will need a little bit of work to figure a way around. I'll keep you updated, this will possibly be resolved but will take some time.

**Comment by kishwarshafin** [comment]
@sonaida ,

Just released a new version, this should resolve your issue. Please feel free to re-open if you still face the same issue
