### ISSUE TITLE
Problem with singularity

### ISSUE THREAD

**Issue by huangnengCSU** [kishwarshafin/pepper#41]
Hi,
    I ran pepper SV detection pipeline on hpc which only supports singularity. And I created the corresponding Input and Output folders in advance.

- The BAM file and REF file were in the folder "/public/home/hpc/userdata/HG003/120G/input/data".

- The output folder "/public/home/hpc/userdata/HG003/120G/output" was also created.

Then I ran the command as follows:
```
[hpc@ln01 ~]$ BASE="/public/home/hpc/userdata/HG003/120G/"
[hpc@ln01 ~]$ INPUT_DIR="${BASE}/input/data"
[hpc@ln01 ~]$ REF="GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna"
[hpc@ln01 ~]$ BAM="hg003_120G.bam"
[hpc@ln01 ~]$ THREADS="48"
[hpc@ln01 ~]$ OUTPUT_DIR="${BASE}/output"
[hpc@ln01 ~]$ OUTPUT_PREFIX="pepper"
[hpc@ln01 ~]$ OUTPUT_VCF="pepper.vcf.gz"
[hpc@ln01 ~]$ singularity exec --bind /usr/lib/locale/ \
> pepper_deepvariant_r0.4.sif \
> run_pepper_margin_deepvariant call_variant \
> -b "${INPUT_DIR}/${BAM}" \
> -f "${INPUT_DIR}/${REF}" \
> -o "${OUTPUT_DIR}" \
> -p "${OUTPUT_PREFIX}" \
> -t ${THREADS} \
> --ont
[03-20-2021 11:07:31] INFO: VARIANT CALLING MODULE SELECTED
[03-20-2021 11:07:31] INFO: [1/8] RUNNING THE FOLLOWING COMMAND
-------
mkdir -p /public/home/hpc/userdata/HG003/120G//output; 
mkdir -p /public/home/hpc/userdata/HG003/120G//output/logs; 
mkdir -p /public/home/hpc/userdata/HG003/120G//output/intermediate_files;
-------
mkdir: cannot create directory '/public/home/hpc/userdata': File exists
mkdir: cannot create directory '/public/home/hpc/userdata': File exists
mkdir: cannot create directory '/public/home/hpc/userdata': File exists
[03-20-2021 11:07:31] ERROR: None]
Traceback (most recent call last):
  File "/usr/local/bin/run_pepper_margin_deepvariant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 732, in main
    run_variant_calling(flags)
  File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 376, in run_variant_calling
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir -p /public/home/hpc/userdata/HG003/120G//output; 
mkdir -p /public/home/hpc/userdata/HG003/120G//output/logs; 
mkdir -p /public/home/hpc/userdata/HG003/120G//output/intermediate_files;' returned non-zero exit status 1.
```
Can you help me. Whether I ran the command mistakenly or there is a bug.

Best,
Neng Huang

**Comment by huangnengCSU** [comment]
Hi,
    I moved the input data into the same folder as the example. Then the code runs successfully. Here is my command, and the difference between the successful version and the failed version is the directory of BASE, INPUT_DIR and OUTPUT_DIR.
```
BASE="${HOME}/ont-quickstart"

# Set up input data
INPUT_DIR="${BASE}/input/120G"
REF="GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna"
BAM="hg003_120G.bam"

# Set the number of CPUs to use
THREADS="48"

# Set up output directory
OUTPUT_DIR="${BASE}/output_120G"
OUTPUT_PREFIX="pepper_hg003_120G"
OUTPUT_VCF="pepper_hg003_120G.vcf.gz"


# Run PEPPER-Margin-DeepVariant
singularity exec --bind /usr/lib/locale/ \
pepper_deepvariant_r0.4.sif \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}" \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t ${THREADS} \
--ont
```

Best
Neng Huang

**Comment by kishwarshafin** [comment]
Hi @huangnengCSU ,

You are right, it's a bug in the pipeline deployment script, I have tracked and reproduced the error on my end. Thank you for reporting it and as you have already solved the issue I'll take a little bit of time to fix this properly. As you can guess, the issue is the pipeline is trying to create a directory, I don't think it should create the directory and the expected behavior is for the user to create the directory. Thank you for reporting it, appreciate the effort you have put into solving the issue.
