### ISSUE TITLE
No module named pepper.pepper

### ISSUE THREAD

**Issue by mrmrwinter** [kishwarshafin/pepper#53]
Hi, I have installed pepper polish through pip, but when trying to use it i get the following error.

```
Traceback (most recent call last):
  File "/home/531734/.conda/envs/ont_assembly/bin/pepper", line 5, in <module>
    from pepper.pepper import main
ModuleNotFoundError: No module named 'pepper.pepper'

```
Sorry if this is something simple that im missing. 
Any ideas?

**Comment by kishwarshafin** [comment]
Hi @mrmrwinter ,

If you are trying to polish a nanopore assembly, please follow this documentation: https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_polishing.md

**Comment by mrmrwinter** [comment]
Thanks kishwar,

Ive tried that and it gets running but fails with the following output.

```
Singularity> run_pepper_margin_deepvariant polish_assembly -b input/data/HG002_ONT_50x_2_Shasta_assembly.chr20.bam -f input/data/HG002_Shasta_run1.chr20.fa -o output -t 28 -s HG002 --ont
[05-07-2021 09:12:14] INFO: ASSEMBLY POLISHING MODULE SELECTED
[05-07-2021 09:12:14] INFO: [1/8] RUNNING THE FOLLOWING COMMAND
-------
mkdir -p output;
mkdir -p output/logs;
mkdir -p output/intermediate_files;
-------
[05-07-2021 09:12:14] INFO: [2/8] RUNNING THE FOLLOWING COMMAND
-------
time pepper_snp call_variant -b input/data/HG002_ONT_50x_2_Shasta_assembly.chr20.bam -f input/data/HG002_Shasta_run1.chr20.fa -t 28 -m /opt/pepper_models/PEPPER_SNP_R941_ONT_V4.pkl -o output/pepper_snp/ -s HG002 -w 4 -bs 64 --ont 2>&1 | tee output/logs/1_pepper_snp.log
-------
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 5, in <module>
    from pepper_snp.pepper_snp import main
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 5, in <module>
    from pepper.version import __version__
ModuleNotFoundError: No module named 'pepper.version'

real    0m1.009s
user    0m1.242s
sys     0m2.299s
[05-07-2021 09:12:15] INFO: [3/8] RUNNING THE FOLLOWING COMMAND
-------
mv output/pepper_snp/*.vcf output/PEPPER_SNP_OUPUT.vcf;
bgzip output/PEPPER_SNP_OUPUT.vcf;
tabix -p vcf output/PEPPER_SNP_OUPUT.vcf.gz;
rm -rf output/pepper_snp/;
echo "CONTIGS FOUND IN PEPPER SNP VCF:";
zcat output/PEPPER_SNP_OUPUT.vcf.gz | grep -v '#' | cut -f1 | uniq
-------
mv: cannot stat 'output/pepper_snp/*.vcf': No such file or directory
[bgzip] No such file or directory: output/PEPPER_SNP_OUPUT.vcf
tbx_index_build failed: output/PEPPER_SNP_OUPUT.vcf.gz
CONTIGS FOUND IN PEPPER SNP VCF:
gzip: output/PEPPER_SNP_OUPUT.vcf.gz: No such file or directory
[05-07-2021 09:12:15] INFO: [4/8] RUNNING THE FOLLOWING COMMAND
-------
time margin phase input/data/HG002_ONT_50x_2_Shasta_assembly.chr20.bam input/data/HG002_Shasta_run1.chr20.fa output/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 28 -V -o output/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee output/logs/2_margin_haplotag.log;
mv output/*.bam output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam;
samtools index -@28 output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam
-------
Could not read from vcf file: output/PEPPER_SNP_OUPUT.vcf.gz


real    0m0.003s
user    0m0.002s
sys     0m0.001s
mv: cannot stat 'output/*.bam': No such file or directory
[E::hts_open_format] Failed to open file "output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam" : No such file or directory
samtools index: failed to open "output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam": No such file or directory
[05-07-2021 09:12:15] ERROR: None]
ERROR ENCOUNTERED IN COMMAND: time margin phase input/data/HG002_ONT_50x_2_Shasta_assembly.chr20.bam input/data/HG002_Shasta_run1.chr20.fa output/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 28 -V -o output/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee output/logs/2_margin_haplotag.log;
mv output/*.bam output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam;
samtools index -@28 output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam
None
```

Any help would be great, thanks.

**Comment by kishwarshafin** [comment]
@mrmrwinter , 

Can you please share the list of commands you are running to get the singularity container? Are you running it from within the container?

**Comment by mrmrwinter** [comment]
Hi, I am running the commands in the ont polishing singularity tutorial and
nothing else.

It begins to run then faild with that error. Does not create the first vcf.

**Comment by kishwarshafin** [comment]
can you please copy-paste the singularity command here? I think there's some copy-paste error somewhere.

**Comment by mrmrwinter** [comment]
Sure, here it is.

singularity exec --bind /usr/lib/locale/ \
pepper_deepvariant_r0.4.sif \
run_pepper_margin_deepvariant polish_assembly \
-b "${INPUT_DIR}/${BAM}" \
-f "${INPUT_DIR}/${ASM}" \
-o "${OUTPUT_DIR}" \
-t ${THREADS} \
-s ${SAMPLE_NAME} \
--ont

**Comment by kishwarshafin** [comment]
@mrmrwinter what OS are you on? I am not sure why this is causing that error. 
Can copy this following code snippet:
```bash
#!/bin/bash 
BASE="${HOME}/ont-quickstart"

# Set up input data
INPUT_DIR="${BASE}/input/data"
REF="GRCh38_no_alt.chr20.fa"
BAM="HG002_ONT_50x_2_GRCh38.chr20.quickstart.bam"

# Set the number of CPUs to use
THREADS="1"

# Set up output directory
OUTPUT_DIR="${BASE}/output"
OUTPUT_PREFIX="HG002_ONT_50x_2_GRCh38_PEPPER_Margin_DeepVariant.chr20"
OUTPUT_VCF="HG002_ONT_50x_2_GRCh38_PEPPER_Margin_DeepVariant.chr20.vcf.gz"
TRUTH_VCF="HG002_GRCh38_1_22_v4.2.1_benchmark.quickstart.vcf.gz"
TRUTH_BED="HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.quickstart.bed"

## Create local directory structure
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"

# Download the data to input directory
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/quickstart_data/HG002_ONT_50x_2_GRCh38.chr20.quickstart.bam
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/quickstart_data/HG002_ONT_50x_2_GRCh38.chr20.quickstart.bam.bai
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/quickstart_data/GRCh38_no_alt.chr20.fa
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/quickstart_data/GRCh38_no_alt.chr20.fa.fai
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/quickstart_data/HG002_GRCh38_1_22_v4.2.1_benchmark.quickstart.vcf.gz
wget -P ${INPUT_DIR} https://storage.googleapis.com/pepper-deepvariant-public/quickstart_data/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.quickstart.bed

# Pull the docker images
singularity pull docker://jmcdani20/hap.py:v0.3.12
singularity pull docker://kishwars/pepper_deepvariant:r0.4

# Run PEPPER-Margin-DeepVariant
singularity exec --bind /usr/lib/locale/ \
pepper_deepvariant_r0.4.sif \
run_pepper_margin_deepvariant call_variant \
-b "${INPUT_DIR}/${BAM}" \
-f "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}" \
-p "${OUTPUT_PREFIX}" \
-t ${THREADS} \
-r chr20:1000000-1020000 \
--ont

# Run hap.py
singularity exec --bind /usr/lib/locale/ \
hap.py_v0.3.12.sif \
/opt/hap.py/bin/hap.py \
${INPUT_DIR}/${TRUTH_VCF} \
${OUTPUT_DIR}/${OUTPUT_VCF} \
-f "${INPUT_DIR}/${TRUTH_BED}" \
-r "${INPUT_DIR}/${REF}" \
-o "${OUTPUT_DIR}/happy.output" \
--pass-only \
-l chr20:1000000-1020000 \
--engine=vcfeval \
--threads="${THREADS}"
```
and do this:
```bash
touch pepper_test.sh
nano pepper_test.sh
*paste*
ctrl + X -> Y
bash pepper_test.sh
```
and see if it runs without any issues?

**Comment by mrmrwinter** [comment]
Hi Kishwar,

It fails with the same error as before, here:

[05-10-2021 09:36:15] INFO: [2/8] RUNNING THE FOLLOWING COMMAND
-------
time pepper_snp call_variant -b
/home/531734/mike/ont-quickstart/input/data/HG002_ONT_50x_2_GRCh38.chr20.quickstart.bam
-f /home/531734/mike/ont-quickstart/input/data/GRCh38_no_alt.chr20.fa -t 28
-m /opt/pepper_models/PEPPER_SNP_R941_ONT_V4.pkl -o
/home/531734/mike/ont-quickstart/output/pepper_snp/ -r
chr20:1000000-1020000 -s Sample -w 4 -bs 64 --ont 2>&1 | tee
/home/531734/mike/ont-quickstart/output/logs/1_pepper_snp.log
-------
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 5, in <module>
    from pepper_snp.pepper_snp import main
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py",
line 5, in <module>
    from pepper.version import __version__
ModuleNotFoundError: No module named 'pepper.version'

Thanks

Mike

**Comment by kishwarshafin** [comment]
@mrmrwinter ,

What OS are you on?

**Comment by mrmrwinter** [comment]
This is on both Ubuntu 20 and CentOS

**Comment by kishwarshafin** [comment]
@mrmrwinter what singularity version are you using? I have tried this is on two different GCP instances with centOS and Ubuntu, I can't re-generate the error.

**Comment by mrmrwinter** [comment]
Singularity 3.5.3

**Comment by kishwarshafin** [comment]
@mrmrwinter , do you have access to docker in your machine? I am not sure how to help in a non-reproducible error.

**Comment by mrmrwinter** [comment]
I can on the Ubuntu machine but not on the CentOS. I will test installing
it with Docker using the instructions on the github and report back

**Comment by kishwarshafin** [comment]
Closing due to lack of activity, please reopen if you have trouble.
