### ISSUE TITLE
.nfs error with singularity GPU

### ISSUE THREAD

**Issue by RichardCorbett** [kishwarshafin/pepper#68]
Hi folks,

I am able to run pepper_deepvariant on a CPU machine with the following command:
```
/usr/bin/singularity exec -B /projects/alignment_references/Homo_sapiens/hg19a_phage_lambda/genome/fasta/:/fasta,/projects/rcorbettprj2/2019FFPE/scratch /gsc/software/linux-x86_64-centos7/pepper-margin-deepvariant-0.4/pepper_deepvariant_r0.4.sif run_pepper_margin_deepvariant call_variant -b F16406.sorted.bam -f /fasta/hg19a_phage_lambda.fa --output_vcf=out_dv.vcf -t 48 -o dv_out --ont
```
This command gives me the high quality SNVs you have in your documentation, so thank you very much for creating this tool.

It took about 24 hours using 48 threads to run the command above, so I wanted to try running on a GPU server to see how much I might be able to speed it up.   With this command I am getting .nfs errors.   My command and output are below...
```
/opt/singularity-3.7.3/bin/singularity exec --nv -B /projects/alignment_references/Homo_sapiens/hg19a_phage_lambda/genome/fasta/:/fasta,/projects/rcorbettprj2/2019FFPE/scratch /gsc/software/linux-x86_64-centos7/pepper-margin-deepvariant-0.4/pepper_deepvariant_r0.4.sif run_pepper_margin_deepvariant call_variant -b F16406.sorted.bam -f /fasta/hg19a_phage_lambda.fa --output_vcf=out_dv_GPU.vcf -t 48 -o dv_out_GPU --ont --gpus all -g

...
[06-01-2021 14:09:15] INFO:  640/646 COMPLETE (99%) [ELAPSED TIME: 29 Min 50 Sec]
[06-01-2021 14:09:15] THREAD 0 FINISHED SUCCESSFULLY.
[06-01-2021 14:09:16] FINISHED IMAGE GENERATION
[06-01-2021 14:09:16] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 29 Min 51 Sec
[06-01-2021 14:09:16] STEP 2: RUNNING INFERENCE
[06-01-2021 14:09:16] INFO: PREDICTION OUTPUT: dv_out_GPU/pepper_snp/predictions_06012021_133924/
[06-01-2021 14:09:16] INFO: TOTAL GPU AVAILABLE: 8
[06-01-2021 14:09:16] INFO: AVAILABLE GPU DEVICES: [0, 1, 2, 3, 4, 5, 6, 7]
[06-01-2021 14:09:16] INFO: TOTAL CALLERS: 32
[06-01-2021 14:09:16] INFO: TOTAL THREADS PER CALLER: 1
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0000000090e67c1e00000190'
...
```

After this error I get another 30ish errors that look very similar and then it shuts down.

Do you have any ideas about how I might get around this?

**Comment by kishwarshafin** [comment]
@RichardCorbett ,

can you please try adding `--ipc=host` to your command line?

**Comment by RichardCorbett** [comment]
Thanks @kishwarshafin ,

I tried this command:
```
/opt/singularity-3.7.3/bin/singularity exec  --nv -B /projects/alignment_references/Homo_sapiens/hg19a_phage_lambda/genome/fasta/:/fasta,/projects/rcorbettprj2/2019FFPE/scratch /gsc/software/linux-x86_64-centos7/pepper-margin-deepvariant-0.4/pepper_deepvariant_r0.4.sif run_pepper_margin_deepvariant call_variant -b F16406.sorted.bam -f /fasta/hg19a_phage_lambda.fa --output_vcf=out_dv_GPU.vcf -t 48 -o dv_out_GPU --ont --gpus all -g --ipc=host
```

and got the same error.    I also tried providing  `--ipc=host` after `exec` but singularity didn't recognize the host parameter.
```
/opt/singularity-3.7.3/bin/singularity exec --ipc=host  --nv -B /projects/alignment_references/Homo_sapiens/hg19a_phage_lambda/genome/fasta/:/fasta,/projects/rcorbettprj2/2019FFPE/scratch /gsc/software/linux-x86_64-centos7/pepper-margin-deepvariant-0.4/pepper_deepvariant_r0.4.sif run_pepper_margin_deepvariant call_variant -b F16406.sorted.bam -f /fasta/hg19a_phage_lambda.fa --output_vcf=out_dv_GPU.vcf -t 48 -o dv_out_GPU --ont --gpus all -g 
Error for command "exec": invalid argument "host" for "-i, --ipc" flag: strconv.ParseBool: parsing "host": invalid syntax
```

**Comment by kishwarshafin** [comment]
@RichardCorbett , any chance you ran out of disk space in the root directory from where you are running the command from?

**Comment by RichardCorbett** [comment]
Looks like I have lots of space to work with:
```
df -h .
Filesystem                                         Size  Used Avail Use% Mounted on
isaac-n16.bcgsc.ca:/rcorbettprj2/2019FFPE/scratch   30T   26T  5.0T  84% /projects/rcorbettprj2/2019FFPE/scratch
```

**Comment by RichardCorbett** [comment]
By the way, it looks as though I get the same .nfs errors when I run in CPU mode, but I still get a .vcf with good results in the output.

**Comment by kishwarshafin** [comment]
@RichardCorbett ,

Unfortunately, I can't generate this error locally. I googled a little bit and it seems like your filesystem mounting with singularity is not properly synced. Are you able to run any GPU-based processes with singularity in your system?

**Comment by RichardCorbett** [comment]
thanks @kishwarshafin.  This is the first attempt I've had with running GPU processes through singularity on our system.  I'll feed this back to our  sys-admins and see if they have any ideas.

**Comment by kishwarshafin** [comment]
thank you, closing this issue for now as it's not reproducible on our end.
