### ISSUE TITLE
" Found no valid reads!" error 

### ISSUE THREAD

**Issue by RichardCorbett** [kishwarshafin/pepper#70]
Hi there,

Thanks for your continued support on helping us to get this working.

I have run a command to distribute the pepper_deepvariant commands such that my genome data is processed in chunks of about 50Mb across my CPU cluster.

One of my chunks is causing some difficultly, yielding what looks like some intermediate SNP calls, but a later error that says "Found no valid reads!".

My command for the chunk that gives me trouble (this is being run inside singularity):
` run_pepper_margin_deepvariant call_variant         -b F16406.sorted.bam         -f hg19a_phage_lambda.fa         -t 16         -o dv_out_split         --ont          -r NC_001416.1:0-48502         -p pepper_deepvariant_F16406_NC_001416.1_0_48502`

```Command exit status:

Command output:
  [06-06-2021 16:54:49] INFO: PREDICTION OUTPUT: dv_out_split/pepper_snp/predictions_06062021_165433/
  [06-06-2021 16:54:50] INFO: DISTRIBUTED CPU SETUP.
  [06-06-2021 16:54:50] INFO: TOTAL CALLERS: 16
  [06-06-2021 16:54:50] INFO: THREADS PER CALLER: 1
  [06-06-2021 16:54:50] INFO: MODEL LOADING TO ONNX
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_15_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_8_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_10_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_1_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_5_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_14_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_12_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_6_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_11_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_3_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_13_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_7_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_4_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_9_06062021_165434.hdf
  WARN: NO IMAGES FOUND IN FILE: dv_out_split/pepper_snp/images_06062021_165433/pepper_snp_images_thread_2_06062021_165434.hdf
  Traceback (most recent call last):
    File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
      finalizer()
    File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
      res = self._callback(*self._args, **self._kwargs)
    File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
      _rmtree_safe_fd(fd, path, onerror)
    File "/usr/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
      onerror(os.unlink, fullname, sys.exc_info())
    File "/usr/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
      os.unlink(name, dir_fd=topfd)
  OSError: [Errno 16] Device or resource busy: '.nfs0000000090bb59ab00001431'
  [06-06-2021 16:54:58] INFO: THREAD 0 FINISHED SUCCESSFULLY.
  [06-06-2021 16:54:58] INFO: FINISHED PREDICTION
  [06-06-2021 16:54:58] INFO: ELAPSED TIME: 0 Min 8 Sec
  [06-06-2021 16:54:58] INFO: PREDICTION FINISHED SUCCESSFULLY. 
  [06-06-2021 16:54:58] TOTAL ELAPSED TIME FOR INFERENCE: 0 Min 8 Sec
  [06-06-2021 16:54:58] STEP 3: RUNNING FIND CANDIDATES
  [06-06-2021 16:54:58] INFO: PREDICTION OUTPUT: dv_out_split/pepper_snp/
  [06-06-2021 16:55:00] INFO: PROCESSING CONTIG: NC_001416.1
  [06-06-2021 16:55:28] INFO: FINISHED PROCESSING NC_001416.1, TOTAL CANDIDATES FOUND: 7.
  [06-06-2021 16:55:28] TOTAL ELAPSED TIME FOR VARIANT CALLING: 0 Min 54 Sec
  CONTIGS FOUND IN PEPPER SNP VCF:
  NC_001416.1
  Running OpenMP with 16 threads.
  > Parsing model parameters from file: /opt/margin_dir/params/misc/allParams.ont_haplotag.json
  > Parsed 7 HET VCF entries from dv_out_split/PEPPER_SNP_OUPUT.vcf.gz; skipped 0 for region, 0 for not being PASS, 7 for being homozygous, 0 for being INDEL
  > Set up bam chunker in 1s with chunk size 100000 and overlap 10000 (for region=NC_001416.1:0-48502), resulting in 0 total chunks
  > Found no valid reads!

Command error:
  [06-06-2021 16:54:31] INFO: VARIANT CALLING MODULE SELECTED
  [06-06-2021 16:54:31] INFO: [1/8] RUNNING THE FOLLOWING COMMAND
  -------
  mkdir -p dv_out_split; 
  mkdir -p dv_out_split/logs; 
  mkdir -p dv_out_split/intermediate_files;
  -------
  [06-06-2021 16:54:31] INFO: [2/8] RUNNING THE FOLLOWING COMMAND
  -------
  time pepper_snp call_variant -b F16406.sorted.bam -f hg19a_phage_lambda.fa -t 16 -m /opt/pepper_models/PEPPER_SNP_R941_ONT_V4.pkl -o dv_out_split/pepper_snp/ -r NC_001416.1:0-48502 -s Sample -w 4 -bs 64 --ont 2>&1 | tee dv_out_split/logs/1_pepper_snp.log
  -------
  
  real	0m57.066s
  user	0m30.763s
  sys	0m10.049s
  [06-06-2021 16:55:28] INFO: [3/8] RUNNING THE FOLLOWING COMMAND
  -------
  mv dv_out_split/pepper_snp/*.vcf dv_out_split/PEPPER_SNP_OUPUT.vcf; 
  bgzip dv_out_split/PEPPER_SNP_OUPUT.vcf; 
  tabix -p vcf dv_out_split/PEPPER_SNP_OUPUT.vcf.gz; 
  rm -rf dv_out_split/pepper_snp/; 
  echo "CONTIGS FOUND IN PEPPER SNP VCF:"; 
  zcat dv_out_split/PEPPER_SNP_OUPUT.vcf.gz | grep -v '#' | cut -f1 | uniq
  -------
  [06-06-2021 16:55:29] INFO: [4/8] RUNNING THE FOLLOWING COMMAND
  -------
  time margin phase F16406.sorted.bam hg19a_phage_lambda.fa dv_out_split/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 16 -r NC_001416.1:0-48502 -V -o dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee dv_out_split/logs/2_margin_haplotag.log;
  mv dv_out_split/*.bam dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam; 
  samtools index -@16 dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam
  -------
  
  real	0m0.706s
  user	0m4.375s
  sys	0m0.222s
  mv: cannot stat 'dv_out_split/*.bam': No such file or directory
  [E::hts_open_format] Failed to open file "dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam" : No such file or directory
  samtools index: failed to open "dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam": No such file or directory
  [06-06-2021 16:55:30] ERROR: None]
  Traceback (most recent call last):
    File "/usr/local/bin/run_pepper_margin_deepvariant", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 732, in main
      run_variant_calling(flags)
    File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 376, in run_variant_calling
      subprocess.check_call(command, shell=True, executable='/bin/bash')
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'time margin phase F16406.sorted.bam hg19a_phage_lambda.fa dv_out_split/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 16 -r NC_001416.1:0-48502 -V -o dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee dv_out_split/logs/2_margin_haplotag.log;
  mv dv_out_split/*.bam dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam; 
  samtools index -@16 dv_out_split/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam' returned non-zero exit status 1.
```

This `NC_001416.1` chromosome is our lambda spike-in that we add to control for chimerically aligned fragments.   is it possible I am running into trouble here because there are no heterozygous variants on my NC_001416.1 chromosome?

**Comment by tpesout** [comment]
Hi Richard,

From the log message, it looks like there are some het variants produced by PEPPER SNP so I don't think that's the problem.  Especially as it's a spike-in, I suspect that the map quality scores may be below 10 and those reads are getting filtered by margin.  Can you run these commands on your bam and report back the output?

```
samtools view YOUR.bam NC_001416.1:0-48502 | wc -l
samtools view -F 0x904 YOUR.bam NC_001416.1:0-48502 | wc -l
samtools view -F 0x904 -q 10 YOUR.bam NC_001416.1:0-48502 | wc -l
```

**Comment by RichardCorbett** [comment]
Thanks @tpesout ,
```
samtools view F16406.sorted.bam NC_001416.1:0-48502 | wc -l
99122
samtools view -F 0x904 F16406.sorted.bam NC_001416.1:0-48502 | wc -l
94864
samtools view -F 0x904 -q 10 F16406.sorted.bam NC_001416.1:0-48502 | wc -l
94842
```

I suppose another possibility is that the coverage is too high?    I should note also, that if I run the command I posted 2 comments above on my whole bam at once I do get all the expected and correct output.

**Comment by tpesout** [comment]
Hmm, ya it's interesting that it works on the whole bam.  Just to clarify, you meant that you break it up into 50kb chunks, not 50Mb, right?  Is there a reason you're doing this experiment 

If you're comfortable sharing the NC_001416.1 data (ref, bam, and preferably the PEPPER_SNP_OUTPUT.vcf.gz file) I can take a look.

**Comment by RichardCorbett** [comment]
I am using 50Mb chunks, but ends of chromosomes or smaller chromosomes end up with smaller bins.  In other words, any remainder after dividing a chromosome by 50Mb gets its own job.

I tried splitting it up into regions to make it faster.   It took just over 24 hours using 48 threads to get results for my 35X bam (is this close to expectation?).  The results were high quality, but I have access to many more CPUS through our cluster and other tools in my pipeline complete in just a few hours.           

I'll look into getting permission to share the data.    I'd give it a 50% chance of being approved.

**Comment by RichardCorbett** [comment]
Good news.  I have permission to share the data.  How would you like me to get them to you?

**Comment by tpesout** [comment]
The timing is close to our expectations; with 96 CPUs it took us 13h on 50x data.  The CPU utilization should be very high, so I think you'll only see speedup if you shard across multiple nodes.  In that case it might be easier to shard across contigs instead of 50Mb chunks, but regardless we'd be interested to hear how your sharded runs come out.

Great!  You're welcome to send me an email at tpesout@ucsc.edu in lieu of putting it here.  A link to a google drive location might be the easiest secure way?  If you just send me that one contig's data I think it'll be all I need to debug.

**Comment by tpesout** [comment]
Thanks Richard, the issue is that there were no HETs found.  The log message in margin incorrectly reported the total number of calls (pre-filtering) when it should have reported total number of usable calls.  Furthermore, it looks like the reads in this region are almost all aligned to the last 2kb, so there will probably be issues in phasing regardless.  

This specific run gives a failure because margin will fail if there's no work it can do, but will just ignore regions where there's nothing to do as long as there are regions where it can phase reads.
