### ISSUE TITLE
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

### ISSUE THREAD

**Issue by siupenyau** [kishwarshafin/pepper#81]
Hi Thank you for sharing this nice tool.

We tried to polish the assembled sequences assembled with Shasta. The sequencing reads were then mapped to the assembled sequences with minimap2. Then we polished the assembled sequences with the following command:

python3 -m pepper.pepper polish -b  sampleID.bam -f Assembly.fasta -m /home/user/pepper_model/pepper_r941_guppy305_microbial.pkl -o sampleID_polished

Then an error was reported:
[07-21-2021 15:49:19]  INFO: POLISH MODULE SELECTED
[07-21-2021 15:49:19] INFO: RUN-ID: 07212021_154919
[07-21-2021 15:49:19] INFO: IMAGE OUTPUT: sampleID_polished/images_07212021_154919/
[07-21-2021 15:49:19] STEP 1: GENERATING IMAGES
[07-21-2021 15:49:19] INFO: COMMON CONTIGS FOUND: ['0', '2', '4', '6', '8']
[07-21-2021 15:49:19] INFO: TOTAL CONTIGS: 5 TOTAL INTERVALS: 2659
[07-21-2021 15:49:19] INFO: STARTING THREAD: 0 FOR 532 INTERVALS
[07-21-2021 15:49:19] INFO: STARTING THREAD: 1 FOR 532 INTERVALS
[07-21-2021 15:49:19] INFO: STARTING THREAD: 2 FOR 532 INTERVALS
[07-21-2021 15:49:19] INFO: STARTING THREAD: 3 FOR 532 INTERVALS
[07-21-2021 15:49:19] INFO: STARTING THREAD: 4 FOR 531 INTERVALS
[07-21-2021 15:50:34] INFO: [THREAD 01] 100/532 COMPLETE (18%) [ELAPSED TIME: 1 Min 14 Sec]
[07-21-2021 15:50:34] INFO: [THREAD 02] 100/532 COMPLETE (18%) [ELAPSED TIME: 1 Min 15 Sec]
[07-21-2021 15:50:35] INFO: [THREAD 04] 100/531 COMPLETE (18%) [ELAPSED TIME: 1 Min 15 Sec]
[07-21-2021 15:50:36] INFO: [THREAD 03] 100/532 COMPLETE (18%) [ELAPSED TIME: 1 Min 16 Sec]
[07-21-2021 15:50:52] INFO: [THREAD 00] 100/532 COMPLETE (18%) [ELAPSED TIME: 1 Min 32 Sec]
[07-21-2021 15:52:03] INFO: [THREAD 04] 200/531 COMPLETE (37%) [ELAPSED TIME: 2 Min 43 Sec]
[07-21-2021 15:52:03] INFO: [THREAD 01] 200/532 COMPLETE (37%) [ELAPSED TIME: 2 Min 43 Sec]
[07-21-2021 15:52:04] INFO: [THREAD 03] 200/532 COMPLETE (37%) [ELAPSED TIME: 2 Min 44 Sec]
[07-21-2021 15:52:15] INFO: [THREAD 02] 200/532 COMPLETE (37%) [ELAPSED TIME: 2 Min 56 Sec]
[07-21-2021 15:52:19] INFO: [THREAD 00] 200/532 COMPLETE (37%) [ELAPSED TIME: 3 Min 0 Sec]
[07-21-2021 15:53:39] INFO: [THREAD 01] 300/532 COMPLETE (56%) [ELAPSED TIME: 4 Min 19 Sec]
[07-21-2021 15:53:39] INFO: [THREAD 03] 300/532 COMPLETE (56%) [ELAPSED TIME: 4 Min 19 Sec]
[07-21-2021 15:53:40] INFO: [THREAD 04] 300/531 COMPLETE (56%) [ELAPSED TIME: 4 Min 20 Sec]
[07-21-2021 15:53:53] INFO: [THREAD 02] 300/532 COMPLETE (56%) [ELAPSED TIME: 4 Min 33 Sec]
[07-21-2021 15:53:56] INFO: [THREAD 00] 300/532 COMPLETE (56%) [ELAPSED TIME: 4 Min 37 Sec]
[07-21-2021 15:55:05] INFO: [THREAD 01] 400/532 COMPLETE (75%) [ELAPSED TIME: 5 Min 45 Sec]
[07-21-2021 15:55:06] INFO: [THREAD 03] 400/532 COMPLETE (75%) [ELAPSED TIME: 5 Min 46 Sec]
[07-21-2021 15:55:07] INFO: [THREAD 04] 400/531 COMPLETE (75%) [ELAPSED TIME: 5 Min 47 Sec]
[07-21-2021 15:55:21] INFO: [THREAD 02] 400/532 COMPLETE (75%) [ELAPSED TIME: 6 Min 2 Sec]
[07-21-2021 15:55:31] INFO: [THREAD 00] 400/532 COMPLETE (75%) [ELAPSED TIME: 6 Min 11 Sec]
[07-21-2021 15:56:23] INFO: [THREAD 01] 500/532 COMPLETE (93%) [ELAPSED TIME: 7 Min 3 Sec]
[07-21-2021 15:56:25] INFO: [THREAD 03] 500/532 COMPLETE (93%) [ELAPSED TIME: 7 Min 5 Sec]
[07-21-2021 15:56:25] INFO: [THREAD 04] 500/531 COMPLETE (94%) [ELAPSED TIME: 7 Min 5 Sec]
[07-21-2021 15:56:41] INFO: [THREAD 02] 500/532 COMPLETE (93%) [ELAPSED TIME: 7 Min 21 Sec]
[07-21-2021 15:56:44] INFO: THREAD 1 FINISHED SUCCESSFULLY.
[07-21-2021 15:56:44] INFO: THREAD 4 FINISHED SUCCESSFULLY.
[07-21-2021 15:56:44] INFO: THREAD 3 FINISHED SUCCESSFULLY.
[07-21-2021 15:57:00] INFO: THREAD 2 FINISHED SUCCESSFULLY.
[07-21-2021 15:57:01] INFO: [THREAD 00] 500/532 COMPLETE (93%) [ELAPSED TIME: 7 Min 41 Sec]
[07-21-2021 15:57:19] INFO: THREAD 0 FINISHED SUCCESSFULLY.
[07-21-2021 15:57:19] INFO: FINISHED IMAGE GENERATION
[07-21-2021 15:57:19] INFO: ELAPSED TIME: 7 Min 59 Sec
[07-21-2021 15:57:19] STEP 2: RUNNING INFERENCE
[07-21-2021 15:57:19] INFO: PREDICTION OUTPUT: sampleID_polished/predictions_07212021_154919/
[07-21-2021 15:57:19] INFO: DISTRIBUTED CPU SETUP
[07-21-2021 15:57:19] INFO: SETUP: 
[07-21-2021 15:57:19] INFO: TOTAL CALLERS: 5
[07-21-2021 15:57:19] INFO: THREADS PER CALLER: 1
[07-21-2021 15:57:19] INFO: DATA-LOADER PER CALLER: 4
[07-21-2021 15:57:19] INFO: MODEL LOADING TO ONNX
ERROR: can't concat str to bytes
ERROR: can't concat str to bytes
ERROR: can't concat str to bytes
ERROR: can't concat str to bytes
ERROR: can't concat str to bytes
[07-21-2021 15:57:25] INFO: FINISHED PREDICTION
[07-21-2021 15:57:25] INFO: ELAPSED TIME: 0 Min 6 Sec
[07-21-2021 15:57:25] INFO: PREDICTION GENERATED SUCCESSFULLY.
[07-21-2021 15:57:25] STEP 3: RUNNING STITCH
[07-21-2021 15:57:25] INFO: STITCH OUTPUT: sampleID_polished/
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/lib/python3.8/site-packages/pepper/pepper.py", line 377, in <module>
    main()
  File "/home/user/anaconda3/lib/python3.8/site-packages/pepper/pepper.py", line 318, in main
    polish(FLAGS.bam,
  File "/home/user/anaconda3/lib/python3.8/site-packages/pepper/modules/python/polish.py", line 115, in polish
    perform_stitch(prediction_output_directory,
  File "/home/user/anaconda3/lib/python3.8/site-packages/pepper/modules/python/perform_stitch.py", line 49, in perform_stitch
    with h5py.File(prediction_file, 'r') as hdf5_file:
  File "/home/user/anaconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/user/anaconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

Would you please let me know if there is something wrong with the model files or h5py files? The sequencing reads were basecalled in hac mode with Guppy v 5.0.11.

With best wishes,

Timothy Ng

**Comment by kishwarshafin** [comment]
@siupenyau, 

The polishing strategy is a bit different now, we use DeepVariant to polish the assembly. Please see here:

https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_docker/ONT_polishing.md
