### ISSUE TITLE
how to get the phased vcf?

### ISSUE THREAD

**Issue by RichardCorbett** [kishwarshafin/pepper#84]
Hi there,

My container:
`pepper_deepvariant_test-v0.5.sif`

My command:
```
run_pepper_margin_deepvariant call_variant \
        -b ${bam_file} \
        -f ${reference_file} \
        -t 16 \
        -o dv_out \
        --ont  \
        --phased_output​ \
        --gvcf
```

My output file list:
```
./logs
./logs/1_pepper_snp.log
./logs/2_margin_haplotag.log
./logs/3_pepper_hp.log
./logs/4_DeepVariant.log
./intermediate_files
./intermediate_files/PEPPER_HP_OUPUT.vcf.gz
./intermediate_files/PEPPER_HP_OUPUT.vcf.gz.tbi
./intermediate_files/PEPPER_SNP_OUPUT.vcf.gz
./intermediate_files/PEPPER_SNP_OUPUT.vcf.gz.tbi
./intermediate_files/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam
./intermediate_files/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam.bai
./intermediate_files/MARGIN_PHASED.PEPPER_SNP_MARGIN.chunks.csv
./PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.vcf.gz
./PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.g.vcf.gz
./PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.vcf.gz.tbi
./PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.g.vcf.gz.tbi
./PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.visual_report.html
```

I'm looking around for errors in the logs but have only seen an error where deepvariant looks for CUDA, doesn't find it, and defaults to the CPU analysis.   Do you have any tips for how I can get the phased output?

**Comment by RichardCorbett** [comment]
I see a number of these errors/warnings, but the file in which I see them, `3_pepper_hp.log` ends with messages saying everything completed ok.
```
OSError: [Errno 16] Device or resource busy: '.nfs0000000090a37d0400008472'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
```

**Comment by tpesout** [comment]
Hi @RichardCorbett I'm not sure what the error you posted means, but if you have the output files I agree that it worked (except for the last phasing step).  The following margin command should work to phase:
```
margin phase $BAM $REFERENCE $VCF /opt/margin_dir/params/misc/allParams.phase_vcf.json -t $THREADS -o $OUTPUT_NAME -M 
```

I'm not sure what docker version you mean by `pepper_deepvariant_test-v0.5.sif` but something like this command (run from the working dir above) should work.  You will have to modify it to give the container visibility to your reference.   Also note that you don't need to use the already-haplotagged bam; your original bam would work fine, I just don't know the right path to it.

```
docker run -it -v `pwd`:/data -v /path/to/ref/dir:/ref kishwars/pepper_deepvariant:test-v0.5 margin phase /data/intermediate_files/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam /ref/$REFERNCE.fasta /data/PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.vcf.gz /opt/margin_dir/params/misc/allParams.phase_vcf.json -t $THREADS -o /data/PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.MARGIN_PHASE
```

**Comment by RichardCorbett** [comment]
Hi @tpesout ,

`pepper_deepvariant_test-v0.5.sif` was a downloaded singularity container we got when you provided a fix to version 4.  Is a full v0.5 release out now?

I'll try out the margin command and report back about my success.

**Comment by tpesout** [comment]
Ahh, gotcha.  No, we're not fully released with v0.5 yet.  The command to margin hasn't changed, so what I gave you above should work with whatever container version you have.

**Comment by RichardCorbett** [comment]
I'm running the margin command as outlined above and I'm seeing segmentation faults.   Here are a couple of examples:

```
Command error:
  Running OpenMP with 48 threads.
  > Parsing model parameters from file: /opt/margin_dir/params/misc/allParams.phase_vcf.json
  > Parsed 5825999 HET VCF entries from pepper_deepvariant_0_5_F16406_no_secondary_KG2_merged_unfiltered.vcf.gz; skipped 0 for region, 1284269 for not being PASS, 1603941 for being homozygous, 492931 for being INDEL
  > Set up bam chunker in 101s with chunk size 100000 and overlap 10000 (for region=16,14,9,21,19,Y,2,20,8,11,22,3,12,17,18,6,4,13,X,15,10,5,7,1), resulting in 30088 total chunks
  > Ordering chunks by estimated depth
  > Setup complete, beginning run
  [W::fai_get_val] Reference 8:86707640-86827639 not found in file, returning empty sequence
  .command.sh: line 2: 65509 Segmentation fault      (core dumped) margin phase minimap_2_2_15_F16406_no_secondary_K2G_2.bam_sorted.bam hg19a.fa pepper_deepvariant_0_5_F16406_no_secondary_KG2_merged_unfiltered.vcf.gz /opt/margin_dir/params/misc/allParams.phase_vcf.json -t 48 -o PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.MARGIN_PHASE
```

```
Command error:
  Running OpenMP with 48 threads.
  > Parsing model parameters from file: /opt/margin_dir/params/misc/allParams.phase_vcf.json
  > Parsed 9625198 HET VCF entries from pepper_deepvariant_0_5_F16406_merged_unfiltered.vcf.gz; skipped 0 for region, 3599806 for not being PASS, 1736839 for being homozygous, 524813 for being INDEL
  > Set up bam chunker in 25s with chunk size 100000 and overlap 10000 (for region=16,14,9,21,19,Y,2,20,8,11,22,3,12,17,18,6,4,13,X,15,10,5,7,1), resulting in 30088 total chunks
  > Ordering chunks by estimated depth
  > Setup complete, beginning run
  [W::fai_get_val] Reference 4:49600003-49720002 not found in file, returning empty sequence
  [W::fai_get_val] Reference 4:49100003-49220002 not found in file, returning empty sequence
  .command.sh: line 2: 159444 Segmentation fault      (core dumped) margin phase PAG33026_0p2.bam hg19a.fa pepper_deepvariant_0_5_F16406_merged_unfiltered.vcf.gz /opt/margin_dir/params/misc/allParams.phase_vcf.json -t 48 -o PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.MARGIN_PHASE
```

For the first command I verified that there are reads in the specified region:
```
samtools view minimap_2_2_15_F16406_no_secondary_K2G_2.bam_sorted.bam 8:86707640-86827639 | head -n 1
2f015bb1-e6ff-4b78-a5c7-a4436f51bf06    2048    8       86726452        60      21452H44M1I7M1D4M1D32M1D9M1D9M1D54M1D3M2D25M1I11M1D7M1I5M1I30M1I10M1I3M2I14M3D33M1D40M1D1M3D25M1I25M1D9M1I37M1I23M3D3M1I9M1I14M2D5M3D15M2I45M1D10M1I57M4I5M3I31M1D14M1D66M1D14M2D1M1D18M2I1M5D2M1D11M1I9M3D27M1D2M1D6M1I56M1I27M2D14M4I43M3I35M1D10M3I2M2I26M1D1M3I10M1D21M1I22M1D18M1I9M2D6M2I14M2I6M1I22M1D17M2I54M1D28M2I33M2D5M1I32M2I16M1D12M1D59M1I49M1I1M1I11M1I23M1D57M6I18M1I7M2D15M1I51M4D10M1D4M1D11M2I13M3D7M1D8M2D11M3I9M2I6M1D9M1I11M1I5M1I22M2D28M1I1M1I7M1I4M1D6M2D2M1I4M1D23M1D2M1D8M1I4M1D45M2I8M2I9M1I12M1D8M7D17M1D18M1D19M2D8M3I1M1I8M1D10M1D28M1I10M1I33M3D36M1D4M2I24M1D2M1D3M1I71M1I45M1I96M2I112M1D35M1D47M2I11M2D62M2D6M1D25M1D15M1I8M2I51M1I36M1D37M1D92M1D27M1D9M2I44M1I40M2I9M1D36M1I30M1I3M1D39M3I25M1D2M1D5M1D23M1D17M1I22M1I2M1D70M1D48M1D2M1D19M2D1M1I60M1D12M1D69M1D27M2I20M1I2M1I2M1I19M1I47M1D36M1I17M4D51M4I28M1I19M1D54M13H       *       0       0       GAATTCCCACTGCCCTCTCATCGGCCTGCCCAGAGCTTCGGGCTCCTGGGTGCTGAATGCACAAGCAGGCCTCAGCATTTGTGGACATCGGGCGGAGCCCAGAACAGGGTCCGGCGGTGCCCCCAGCGTGGCCCAAGATGGTGACGGAGTCGTGCTGCTTCCTGCAGAGGGGATCGGCCTGCCGCTTGCCCAGCCGCCGCGGGCTGACCAGAGAAGGCCCTCGGGAGTCCGCATCTCAGCCCCCAAGGAAGAGGAGAAACCCGATCGCCCACTGTAGCCCTTGCTTGGTCACAGGTTACACAGATGCCAGAGAACCCAGGTGACCAGCAGCAGCCAGCGCTCCCGTGGTGGGTCGGCAGACAGCCAGGGAAGACAACGCAACAGGTCAGGGATGGCATGCAGACCACCGCCCACCACCAGCTCTAAGCGAATCGTCCGTCGTCCATCACTTACCGAGTTTGAGTTTGAAGAGCATTTATCCTCCGGCGGCTCTGGGTGCAGTCCCCGTCCTCCGCCGAGGCGCTATCTCCAACTGTTCACCGAAGAGTGTCTCAAGTTCTGCGCCTCAAGCAGGAGAGCCGAGGAGAAGAGGCTGAGCGAGGAGAAGGTGGCCTACGACTGCAGCCCCGGCAAGGAGCACCAGGGAGTACCTGAACGTGGTCCTGAACACCCTCAAGGGCTGAAGGGCCTGGCCCCAGCTCCATGCCCGGCCTCAGCAGGGCCGCCCTGCTTGGCCGCCTCCAGGAGTTCCTGCTCACCGGGACCAGCTCAGGAACGGCTGCCCCTTCCCTTGCGGCGGCCCGGAGAGCGCCGTCCTCACTGGCCAGGGGAAGGAGGCCGGCGCTCTCCTGCCAGGGTCTGCTGCCGTTGTGGCACCGAGTGCCTGGTGTCCTCCTCGGGCCGCTGTGCTGCGCGACCAGTTGTGGTATTATCACTGGGCGGGTCCGCTCTCGAGAGCCAGGTGGCTGGAGGCAGATTTAACCAGTACACCTGCTGTGCAGCAGCTGCTCCTGGCTCTGTGGGCTGCCAGGTGGCAAGCAGCACGTCTTGCCCGGGACGGCCGCAGGAAGAGCCTCCAGCAACCCCCGTGGAACCTTCAAGAAAGAGTTGTCCAAGAGACGCTTGTCCAGGAATCTCGCCTTGGACTGTGAGATATTGCTACACTGCATGGCGCCTAGAGCTGACCCACGCGTCTGCCGTGGTGGACGCCGACATGCAGTGGTGTCTGGCACCTGCTCGTCAAGCCCGACAGCGAGATCGTGGACTACAGCACCAGGTTTTCCGAGGTCACGAGGCCGGCGTCGCCAAGGCAGGCATCCAACGTTGCCCCAAGTCCAAGCCATCCTGCTGAGCTTTCAGGCGCCCAAACCATCCTCATCGGGCACAGCCTGGAGAGAGCGACCTGCTGGCCTGAAGCTCATCACAGCACCGTGGTGGACACGGCCGTGCTCTTCCCGCACTACCTGGGTTCCCCCTACAAGGCGCTCCCTCAGGAATCTCGCGGCCGACTACCTGGCACAGATCATCCAGAGCCCAGCCAGGGCTGGCCACAGCTCCAGCGAGGACGCAACGCCTGCCTGCAGCTGGTGATGTGGAAGGTCCGACAGCGCGCCCAGATCCAGCCACACTTGCGCCACCGGTCCGCCTCTCCCCGCCGCTGGCCTGTCCTTGGCCCCCAGGCCTCTTCCAAAACCGCCATCAGTCCCGAGAGCTCACCCTGCCCACCTGCGCCGCCAGCGAAGAAGCTGGGCAGCGGCCGGCGGCAGAGGGCAAAAGCCAAGTAACCCCAACCCCCCCCCACTCCCCCGGTCCCCGGAATCCCCTGCAGCGGCCCCCTCCAGGCCTGTCCACATCCCTCTGCCTCCCAGACCTCTGTCCTTCCACCAATACAGCCTCCCACCAGCCCGAGGCATACTCCAGTCCCCCGAGTCCCTGCAGCAGCCTCGCGCTCTGTCACATCCCTCTGCCCATCCGAGACCTCTGTCCTTACACCACTAGCCACACCCCACGTGTGGGACTTCCCATAGCTTCTGGTACAAGGCCCGGCCCACCAGCTTTGGAATGCCTGCTTACCTCTTTTCTGTAGAGGCACCACGGAGGTGGAGTGCTGAAGCGCCCGACTCTGGGTTACAGATCTGGGTTCAAGGCCAAATTCCCACCACTTACCTGAGTTTGTAATATTGGACAGATAACGTCTTTCTTCTACCTTTTGGTCTTTAAAGTGTAGTCAGGAGAACTTAAAGACTCCCACATAGTAATATGTATATGTGTGTAAATATAACACCCCACTGTCAACATTAGACACACCAACGAGACAGAAAGTTAAAAAAGGATATCCAAGAGATTGAGCTCAGCTCTGCACCAAGCGGACCTAGGAGACATGTACAGAAACGCTCCACCCCAAATCAACAGAATATACATTCTTCTCAGCACCACATCACACTTATTTCCACATTGACCACATAGTTGGAAGTAAAGCACTCCTCCCAGTAAAAGTAAAATAACAGAAATTATTACAAACAGTCTCTCAGACCACATTGCAATCACACTAGACCTCAGGATTGAGAAACTCACTCAAAACCGCTCAACTGCATGGAAACGGACAAGCTGCTCCTGAATGAGTACTGGGTACATATGAAATGAAGGCAGAAATAAAGATATTCTCTGAAAGCAATGAGAACAAAAAGACACAACACCAGAATCTCTGGGACACATTTAAAGCAGTGTGTAGAGGGAAATTTATAGCACTAAATGCCCTAGGGAAGCAGGAAAGATCAAAAATGCATACCTAACATCACCATTAAAAAGGATTAGAGAGAAGCAAGAGCAAACACATTCAAAAGCTAGCAGAAGGCAAGAAACAACCCAAGATCCGAGCAGAACTGAAGGAGATAGAGACCCAAAAACCCTTCAAAAAATCAATGAATCCAGGAGCGGGTTTTTGAAACCATCAACAAAATTGATGGACCACTAGCAAGACTATTAAAGAATGAAAGAAAGAAGAATCAAGCAGATGCAATAAAAAATGATAAGGGGATATCACCACTGATCCCACAGAGTACAAACTATACCATGAGAGAATACTGTCAACACCTCTAGGCAAACAAACTCGAGAAATCTAGAAGAAATGAATAAATTCCTGGACACATGCAACCCCTCCCCAGGTAAACCAGGAAGAAGTTGAATGCCTGAATAGACCAGCTAACAGGCTCTGAAATTGAGGCAATAATTGTATGCTTCTCAAGCAATAAAACTCCAGGACCAGACGGATTCACAGCAGCCGAATTCTACCAGAAGTACAAGAGAGCTGTACCATTCCTTGGGAAACTATTCAATCAACAGAAAAAGAGGGGAATCCTCCCTATCTCATTTATAGAGGCCAGCATCATCCTGATCCCAAAGTGAGAGAGAGACACAACCAACAAAGAGAATTTTCGGCCCATATCCTGGGGAACACCGATGGAAAAATCCTCCATAAAATGCTGGCAAACTGATCAGCAGCACATCAAGAAACACTCCATTGTGATCAAGTGGGCTTCATCCCTGACATGCAAGGCTGGTCCAACATATACAAATAATAAACATAATCAGCATATAATCGGAACCAAAGACAGAAACCGCGTGATTATCTCAACAGATACAGAAAAGGCCTTTGACAAATTCAACAGCCTTTCATGCCAAAAACTCTCTCAATAAATTAGGTACTAGAGTGAGGACATGCCTCAAAATAATAAAGAACAACCCAGGGCAAACCCACAGCCAATATCATACTGAATGAGCAAAAGTGGAAGCATTCCCTTTGCAAACTGCCATAGGAACAGGGGTGCCCTCTCTGCTCCTATTCAACATGGTGTTGGAACTTCTGGCCAGGGCAATCAGGCAGGAGAAGGAAATAAAAAAAGAGTAATCAATTAGGAGAAAGAGGAAGTCAAATTGTCCTGTTTGTAGATGACACGATTGAATATTTAGAAAACCCCATCGTCTCAGCCCA 1A>CC>=5/9:7;;<97'/)-((*)088467?067./94&+?AB::9/+,'%$()'0--66:<:,))+=7883,79;:;9)//91//58$(+'10)-/.*,(&0--7)<=F>./'(285998:>52;;9;;>@AFA@=9;59B:666%4.433*--&/0130+(,-+*../0/9/+-343058,2443355*99571.(&),50/2-&(--$&''3(?@75:%)/&27;0*))267<(155364/(551//+241-%&%/0.+%02-()+(*/$'&2=@>@?5/241399*,,+7=><<;==:=</++0)9?B>994(371.%)*#$$%.01-44/)2066>A7/00++')10098444:;;68:/53:;4/+&&%1/:?856876:6958?77666/)2()456%('&''%***87;5;<<;80(&)(./4'5?;-/80=B898;8/***--&.17?@A78>77833-'*&&&&&(1<95689*,*+':=;5433&$&%(/21*&&///7<5-..('''#$,--@>><=80<;=BCD.)%(')%(3;8D>?E>32>D<@6CD:<B;:533377+4233/7*+&*$*1.,$+**&%%0.0(56,>88>11)&./$+35:80)(**&&&'',,)$&#*--)*#&$&'.*)4410//.0//1647;99<<;579;:;+2-).&$%1-(1))'(,6>90)=A<==;559;?39:<?<:367,+%&$)66/,+%%'(,.*+339:<8647;:39688664/+,%*;?8<;>;;7&(+(%('+<;/11235500%##%2.&2.1:3-7;:$'/9;,-.;:+1*)*.-333.633)36--$.-03+)''-04'*30.'*(3/==;<:88=784==6&0065-&,%310/.*+/56:98=<8:;*->7(2<<;8-$--','74.7..99=50.0//0,.1-..*,2-/'%%&/4+40/;:/$,&.023@89=C9=>720**+$#%*%$('')*,3.7:>A?=<***)''.21-+%7>8203:<;;455:>899666<?8:31.+)))((')+81330(+**./201/-)((('&((%%*&%,,*(&&+(00.-05:<:>7<=?>::)058+).9HG@@=?:)31613---.$566)0:A?@;>5*)*./468763)-,1)%%%&/03+(($$$$%''%%'/150722503*--+&(+*/-(&(1/5112673-3:+1.4000($$'))+30&##'&$$$&''$+*,688/&20'))&('1038425;=>?=9:199$65--,7:FEG?:=1,-48-$3(%*,.,%*47*058:3/62.,-6::8;7.2//78476767)::9;C<:?@<;<<>>@>A:>;>92./-,<=25,5509<)><;=8:40&:9@BAA>6886)%-0+-+1<99:<:77-363/%(*8;<)'77.14291:;:<=6:=<0.-'(/117>@CD?@@<=).357<:9;9;==9?A@9854,77&,029;9<8775+70333.++*$&1;764D=969798;;?<:<>?:<;0(+(&,..*224.21%(','-.&,)$74>1,324+/251221-9=;;975554-,4>==8797687:;8202;::=1..1355;1211/778;/$32)**'''/-/1//.'*.<?78::<:2A<7-./)*:3149:8<<<613'-7865),2&#-67=<9=:9?912,7;;?@97>@=,*&&((+*,,--+003684.--($$'%($%/%)30-%.,&320-*$$%'''1%3--51--4&:3<<A?5.5566(/-.0468<7(8720200/.-158723+179><943,535DB77<1401((/>=:;<687&/=&463==+%-.9?>6:,/389/63)/53224324<7498=71./6,'&$&)(*8860)&&*,,/.'%&*)%$$3793).;?=99800==9:;93)(*&$)+,33'$(+33--7817@?<:7=:=<88B<=A;119.'8=;=<?<;??40677-1:/5716(8==<8)/27%'+/<=;AB=A/+&&149;?>4&**.%'.871,%&69<6794*3::.*4'1//5630))+-35?3G@;.25-004//8;4))+&&)'06210$7+*$$++/&'%%%%,%:=6:6+8?@,3:.6:=;02=CDCA85337;;?CCCA55988174.*-+)*7EEF02;623662/1))3200.,-31--,**'*$&*+12/$)-:7:9;./321*"#%.-*$'-%%0+,,$%$$-C<:5.15211445.**#$%,))&(%121001(&%*4-))76402<</;93.''&&$)$0**#$$%$$$(:9<;BD:55@@FJF=704;@?8?:2%%-$$044%**137=6=A;B<;?8?A4.*37=797(6><7B=>8:89<85*+/.09?<=:AA>=FFA>>@5<:3/=;:4767BECHH@A<;0898;00-;4*)*015223@@4*67456457.1)45198205399@47;AA??88;9944'**,,.'''(94/0-,-'('223/13/+,:310:=8*/(661=7::66>?,4339660647'/5/03-'..,+,%+$87245)))0<@>B<++68;;<:<<7334463342(8>>:12;;::<>+($%,&%(&**985-1+**(#$++-43555+'-/033C<<>7,+889GFA<543788:79+0055?9=FA9,+1==>;:($'&'1-7@A<(6125<>988:?@<7DF$224----*+.2%'7(1??@@<53678B73-,0///(%(%0@B9&)*1&992;@FBLNQA6++84**:>58752;,08:>BC=61.,12(,.7461*)&'*&72/63<<9>6733FEA=8540A@/,,,16-1>?A26::00:5&/'+;8=;92'(5764?@A88;>789;C:>(16B9=DLNI<>::=@CBD:66=:<=76457=?<<*?0..23.+JD;-),261-..6272:?A@B=>77663810-//'%&,))9679::6.-)A?995340?:20C?<HBC=A12:>/;988923674/<6245992,&*4932&,5;?=<989@;:/3221(,54384++/)'),/2772%)57945AA2?B;=>@79@53((,9-;3//0*=>7/1&0;6>>:31)*6/DA>BFF?F<AFFECB@>B<92,*.;<9222)?B>895+/:;<4585>@=,.***BB:2887:8>26.***>8;;%&250-.,6>@6=7:<9:;8:6:88:56)''&%(('$$%%:72569@>?C?80==>=..6@496185;58650,++'$%+0)--1018<3-.4)*,1344.''($$32/%$&/42;>;-22'),,))&%'&)+%5<>+,/01542(&.,%(::-9=<5=::=76=;.74697'%%%'',7<>9:>A<?AA?<<<@;:(?8)0//055(-045:71%405;:(<=<7.)%(33421),+---'&&232/%%,.0968828:=:3AGG@=?<8?8832A?@@65AC>8757+&%((423.45100(/<55&$&-&'($322767'((&;:B=7++0A>@AB>CEB4448>>66?7<4<>=<098;=4*)8*$$08:0'''(*0+446<8=71+-*./166:678;;694+)))33.083,)*$)&,579:@7<73/225*%%&&&),9..09<@@><628)4;<>B57987:33331..68@@5?8@C9(4A8???C?>>@4/&$$#&'%'*))%'2*,%%$35<>FCIE?HA=A7&)&%%%$$$#%.0;@DD>?B<>=<8=@D<?AC@:534?;BB;;A??CA--+9.)323375,//1999*5.4:9899:+',&&&743</179;1259>*01./:9:;?KHBB+*=9:4997>389556:89597:4??=@C1A?:(1**9;4*-04077*5970**('%%78>@C<;989,67;/B>/*-,)%36;555556:?=<:8BBB49=<>;>>=>13DFEAA>;<AA??4AGIB=>=A@B94?<?95(*,,5 NM:i:411        ms:i:5618       AS:i:5618      nn:i:0   tp:A:P  cm:i:219        s1:i:1742       s2:i:79 de:f:0.0791     SA:Z:8,86554560,-,1947S21891M38I1580S,60,2588;8,86742137,+,28S1382M43D24046S,0,138;     MD:Z:22A28^C1C0C1^G32^C1A7^C9^G50A3^C3^GC34C1^A0A52G13C1^TCC33^A9G4G13A11^C1^CCA0A24G24^A41G27^AAC0C12A0A11^CA5^CCA60^C22G0C5A31A0A5A34^A1A12^A0C37T0A0C0A24^C2A11^AG1^A8A10^CACCC2^A20^TCT18G1C6^A2^C35A27A14T10^GG33C1G0G3G51^A25A1G8G1^T1G1T0T6^G31A11^A18G8^CA0C25A21^G8A0C1A20A17A14G0A4^C8A10A1G0A38^TT53^C12^C49T59A8A8A15^A82^CC13A52^CCAC3C1C4^A0A3^A0A2A2A7A6A2^AGG7^A8^AG26^C15C10G20^CC36G3^C6^CC2C3^C20C2^G0C1^C12^C66G7^A8^CCAGCCC17^C18^T19^AG15A1^T0T2G6^A40A0G29^GCG26G0A3A0A3^G23A0T0A2^A2^A0A3C3C0T60G0G41C116T18G47G29^C35^A1C56^AT62^CA1A4^A25^C70T0T3T34^A37^T14C11A65^A23C3^A102^A36A29A2^A2C1A59^G2^G5^G12C10^C41^T27G0C0T40^C4A41C1^A2^C14A0G1G1^TT7A47G5^C12^C51G17^A57A15G0G1T1T0T0T33G2^A32C1A18^CACC0A14A39G3C38^C54
```

**Comment by RichardCorbett** [comment]
I might have some traction on this.  It seems that when margin fires up it tries to make a .fai index for the reference.   While this is happening, another process is trying to read the file.     If I'm lucky the .fai completes before it gets queried by the other processes, but other times, like above I get those reference errors.

I'm still testing this, but it seems that if I place the corresponding .fai next to my .fa then the .fai doesn't get created and things work more smoothly.

**Comment by tpesout** [comment]
Hmm, ok thanks for continuing looking into this.  In the past couple months, the only issue we've seen with margin failing has been when the bam has mulitple copies of the same read in it.  Keep me posted please on whether this resolves the issue for you

**Comment by RichardCorbett** [comment]
I have been able to run 10 analyses successfully by making sure the .fai file is present with the .fa to keep margin from trying to create it.  Don't want to jinx it but this might be all I needed.

**Comment by kishwarshafin** [comment]
@RichardCorbett , if you think the problem is solved for now then please feel free to close this issue. Also reopen if you observe it again. Thank you very much for navigating this alone, that is much appreciated, it would have been very difficult for us to figure this out on our end as we always have the reference index present in the filesystem by default.

**Comment by RichardCorbett** [comment]
Thanks @kishwarshafin.   I'll let you know if anything changes on my end.
