### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by stefandiederich** [kishwarshafin/pepper#86]
Hi, 

I try to use pepper for variant calling of ONT data aligned with minimap2 (version 2.21). I followed the Nanopore NVIDIA-docker pipeline to install PEPPER and executed it with sequence data of chromosome 22 of NA12878. Unfortunately I get the following error  when executing:

```
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 445, in main
    set_profile)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 116, in call_variant
    threads)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 154, in run_inference
    device_ids)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 87, in polish_genome_distributed_gpu
    predict_distributed_gpu(image_dir, file_chunks, output_dir, model_path, batch_size, total_callers, threads_per_caller, device_ids, num_workers)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 143, in predict_distributed_gpu
    join=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 8 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 121, in setup
    predict(filepath, all_input_files[rank],  output_filepath, model_path, batch_size, num_workers, threads_per_caller, device_ids[rank], rank)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict_distributed_gpu.py", line 66, in predict
    output_base, hidden = transducer_model(image_chunk, hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/simple_model.py", line 30, in forward
    x_out, hidden_out = self.gru_encoder(x, hidden)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 716, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

Have you seen an error like this before and can you help me solving it?
Bests
Stefan

**Comment by kishwarshafin** [comment]
@stefandiederich 

This is happening due to CUDA version mismatch. What CUDA version are you using?

**Comment by stefandiederich** [comment]
@kishwarshafin 
Thanks for you reply. 
`nvidia-smi` tells me CUDA Version 11.1

**Comment by kishwarshafin** [comment]
@stefandiederich ,

Can you please see if you are getting the same error with `r0.5-gpu` docker?

**Comment by kishwarshafin** [comment]
closing this issue, please follow https://github.com/kishwarshafin/pepper/issues/71 which reports the same issue.
