### ISSUE TITLE
CentOS 7 Install 

### ISSUE THREAD

**Issue by carsweshau** [kishwarshafin/pepper#9]
Hello,

I was having an install issue for PEPPER on CentOS 7, using either the `make install` or `pip` methods, where cmake throws this error: `Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)`. I fixed this particular issue by editing the CMakeLists.txt as below (requires cmake>=3.12):

```
#FIND_PACKAGE(PythonInterp 3 REQUIRED)
#FIND_PACKAGE(PythonLibs 3 REQUIRED)
FIND_PACKAGE(Python COMPONENTS Interpreter Development)
```

But then when we enter the pepper virtualenv and run `pepper --help`, the output is as follows:

```
(pepper) -bash-4.2$ pepper --help
Traceback (most recent call last):
  File "/share/ClusterShare/software/contrib/shacar/pepper/venv/bin/pepper", line 33, in <module>
    sys.exit(load_entry_point('pepper-polish==0.0.6', 'console_scripts', 'pepper')())
  File "/share/ClusterShare/software/contrib/shacar/pepper/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/share/ClusterShare/software/contrib/shacar/pepper/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/share/ClusterShare/software/contrib/shacar/pepper/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2461, in load
    return self.resolve()
  File "/share/ClusterShare/software/contrib/shacar/pepper/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/share/ClusterShare/software/contrib/shacar/pepper/pepper/pepper.py", line 5, in <module>
    from pepper.modules.python.polish import polish
  File "/share/ClusterShare/software/contrib/shacar/pepper/pepper/modules/python/polish.py", line 1, in <module>
    from pepper.build import PEPPER
ModuleNotFoundError: No module named 'pepper.build'
```
I acknowledge that CentOS 7 is not the peferred environment, so any help is greatly appreciated.

**Comment by kishwarshafin** [comment]
@carsweshau , are you sure the`PythonLibs` or `PythonInterp` were actually found? Without python3 libraries, pybind can't generate the library and the PEPPER module never gets built. Can you please post the output of these commands:
```bash
python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())"
```

**Comment by carsweshau** [comment]
@kishwarshafin Thank you for the support, here is the requested output:

```
(pepper) -bash-4.2$ python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
/home/shacar/.localpython/lib
(pepper) -bash-4.2$ python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())"
/home/shacar/.localpython/include/python3.6m
```

The local python environment might be complicated, as the CentOS default is not the one I use.

**Comment by kishwarshafin** [comment]
Thanks for bearing with me. Can you please do these steps and upload the log here:
1) go to the pepper directory.
2) activate venv
3) run `python3 setup.py install > install.log` 

and copy the contents of install.log here? I just tried installing PEPPER on a centOS 7 instance on GCP and it finished successfully. I think this is a local setup issue. 

Is there anything other container you use for your system that can wrap a docker?

**Comment by carsweshau** [comment]
Good observation, it does look like a local install issue with CMake, the below output occurs for both cmake version 3.6.1 and cmake version 3.13.2:

2. `make clean`
```
-bash-4.2$ make clean
(. ./venv/bin/activate && python setup.py clean) || echo "Failed to run setup.py clean"
running clean
removing 'build/temp.linux-x86_64-3.6' (and everything under it)
rm -rf venv build dist/ *.egg-info/ __pycache__ *.egg-info
find . -name '*.pyc' -delete
```

3. `virtualenv venv --python=python3 --prompt "(pepper) "`
```
-bash-4.2$ virtualenv venv --python=python3 --prompt "(pepper) "
Running virtualenv with interpreter /home/shacar/work/venv3/bin/python3
Using real prefix '/home/shacar/.localpython'
New python executable in /share/ClusterShare/software/contrib/shacar/pepper/venv/bin/python3
Also creating executable in /share/ClusterShare/software/contrib/shacar/pepper/venv/bin/python
Installing setuptools, pip, wheel...done.
```

4. `source ./venv/bin/activate`

5. `python3 setup.py install > install.log`
```
(pepper) -bash-4.2$ python3 setup.py install > install.log
package init file 'pepper_snp/modules/python/helper/__init__.py' not found (or not a regular file)
package init file 'pepper_hp/__init__.py' not found (or not a regular file)
package init file 'pepper_hp/modules/python/__init__.py' not found (or not a regular file)
package init file 'pepper_hp/modules/python/models/__init__.py' not found (or not a regular file)
warning: no files found matching 'build.sh'
CMake Warning at CMakeLists.txt:13 (FIND_PACKAGE):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python" with any
  of the following names:

    PythonConfig.cmake
    python-config.cmake

  Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
  "Python_DIR" to a directory containing one of the above files.  If "Python"
  provides a separate development package or SDK, be sure it has been
  installed.


Python not found
configure: WARNING: GCS support not enabled: requires libcurl support
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
In file included from ext/_yaml.c:596:0:
ext/_yaml.h:2:18: fatal error: yaml.h: No such file or directory
 #include <yaml.h>
                  ^
compilation terminated.
Error compiling module, falling back to pure Python
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
warning: manifest_maker: MANIFEST.in, line 5: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching '*.html' under directory 'doc'
warning: no files found matching '*.css' under directory 'doc'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/auto_examples'
no previously-included directories found matching 'doc/modules'
no previously-included directories found matching 'doc/reference/generated'
no previously-included directories found matching 'doc/reference/algorithms/generated'
no previously-included directories found matching 'doc/reference/classes/generated'
no previously-included directories found matching 'doc/reference/readwrite/generated'
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
zip_safe flag not set; analyzing archive contents...
future.backports.test.__pycache__.ssl_servers.cpython-36: module references __file__
future.backports.test.__pycache__.support.cpython-36: module references __file__
future.standard_library.__pycache__.__init__.cpython-36: module references __file__
future.standard_library.__pycache__.__init__.cpython-36: module references __path__
future.utils.__pycache__.__init__.cpython-36: module MAY be using inspect.stack
past.builtins.__pycache__.misc.cpython-36: module MAY be using inspect.stack
past.translation.__pycache__.__init__.cpython-36: module references __file__
past.translation.__pycache__.__init__.cpython-36: module references __path__
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
warning: no files found matching '*.yaml' under directory 'demos'
no previously-included directories found matching 'docs/build'
warning: no files found matching 'tornado/test/README'
zip_safe flag not set; analyzing archive contents...
tornado.__pycache__.autoreload.cpython-36: module references __file__
tornado.__pycache__.gen.cpython-36: module references __file__
tornado.__pycache__.options.cpython-36: module references __file__
tornado.__pycache__.speedups.cpython-36: module references __file__
tornado.__pycache__.testing.cpython-36: module references __file__
tornado.test.__pycache__.gen_test.cpython-36: module references __file__
tornado.test.__pycache__.httpserver_test.cpython-36: module references __file__
tornado.test.__pycache__.iostream_test.cpython-36: module references __file__
tornado.test.__pycache__.locale_test.cpython-36: module references __file__
tornado.test.__pycache__.options_test.cpython-36: module references __file__
tornado.test.__pycache__.template_test.cpython-36: module references __file__
tornado.test.__pycache__.web_test.cpython-36: module references __file__
```

Our sys admin is considering singularity on our cluster, but as of yet I don't think I can run any container rootless (was trying to use rootlesskit and dockerd-rootless.sh, but to no avail, alas)!

I'll attempt edits to CMakeLists.txt from the above log - thank you very much for your help, you shouldn't have to spend your time diagnosing my setup! I'll add another comment if I have any luck.

**Comment by kishwarshafin** [comment]
Hi @carsweshau , I have two more suggestions if you have time to try them.

**Solution 1:**
1. Undo the changes you made to `CmakeLists.txt`. And 
```bash
FIND_PACKAGE(PythonInterp 3 REQUIRED)
FIND_PACKAGE(PythonLibs 3 REQUIRED PATHS /home/shacar/.localpython/lib)

message("PYTHON LIBRARY:" ${PYTHON_LIBRARIES})
message("PYTHON INCLUDE DIR:" ${PYTHON_INCLUDE_DIR})
```
From the messages, you should be able to see that both the variables are picked up correctly.

**Solution 2:**
If solution 1 does not work please try this. Make sure that this file exists: `/home/shacar/.localpython/lib/libpython3.6m.dylib` and then please try this:
```bash
FIND_PACKAGE(PythonInterp 3 REQUIRED)
SET(PYTHON_LIBRARIES /home/shacar/.localpython/lib/libpython3.6m.dylib)
SET(PYTHON_INCLUDE_DIR /home/shacar/.localpython/include/python3.6m)

message("PYTHON LIBRARY:" ${PYTHON_LIBRARIES})
message("PYTHON INCLUDE DIR:" ${PYTHON_INCLUDE_DIR})
```

For each of the solutions, make sure you do in these steps:
1. Run `make clean`
2. Change the files
3. Run `make install` or the previous three steps that you were doing by manually generating the `venv`

**Comment by carsweshau** [comment]
@kishwarshafin Thank you for all of your assistance, I have PEPPER polish installed now and will run on my MarginPolish output, will close this issue. Many thanks again for your time and patience!

**Comment by kishwarshafin** [comment]
@carsweshau , glad that it worked. Just so you know, PEPPER is a separate polisher. It does not work on the outputs of marginpolish, it creates its own. 

We developed PEPPER to demonstrate that we don't need a pre-polishing step like Racon or MarginPolish if we have a good enough assembly. If you are running on guppy 3.6.0, it'd be ideal if you can wait for a week, I'm going to upload a model for 3.6.0 soon.
