### ISSUE TITLE
ERROR: Can't determine and Unable to open object (bad local heap signature)

### ISSUE THREAD

**Issue by songbowang125** [kishwarshafin/pepper#97]
Hi, I was running PEPPER-Margin-DeepVariant on ngmlr-aligned ONT data and i met the following errors:

[09-03-2021 21:21:04] INFO: MODEL LOADING TO ONNX
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/dataloader_predict.py", line 51, in __getitem__
    image = hdf5_file['summaries'][image_name]['image'][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad local heap signature)'

I ran 5 examples (same align method and parameters) and only one example met this error

**Comment by kishwarshafin** [comment]
@songbowang12, I'll need a little more details as I have not seen this error before. What command are you running?

**Comment by songbowang125** [comment]
> @songbowang12, I'll need a little more details as I have not seen this error before. What command are you running?
The command is: docker run --ipc=host -v ... kishwars/pepper_deepvariant:r0.5 run_pepper_margin_deepvariant call_variant -b -f -o -p -t --ont. 

And the logs before this error seems correct, which is :

Loaded image: kishwars/pepper_deepvariant:r0.4
Load finish
[09-03-2021 10:13:06] INFO: CALL VARIANT MODULE SELECTED.
[09-03-2021 10:13:06] INFO: ONT PROFILE SET FOR VARIANT CALLING.
[09-03-2021 10:13:07] INFO: RUN-ID: 09032021_101307
[09-03-2021 10:13:07] INFO: IMAGE OUTPUT:
[09-03-2021 10:13:07] STEP 1: GENERATING IMAGES
[09-03-2021 10:13:29] INFO: COMMON CONTIGS FOUND: [chroms]
[09-03-2021 10:13:29] INFO: TOTAL CONTIGS: 224 TOTAL INTERVALS: 31097
[09-03-2021 10:13:29] STARTING THREAD: 0 FOR 1111 INTERVALS
[09-03-2021 10:13:49] INFO:  10/1111 COMPLETE (0%) [ELAPSED TIME: 0 Min 19 Sec]
[09-03-2021 10:15:06] INFO:  20/1111 COMPLETE (1%) [ELAPSED TIME: 1 Min 36 Sec]
...
[09-03-2021 19:39:46] INFO:  1110/1111 COMPLETE (99%) [ELAPSED TIME: 566 Min 17 Sec]
[09-03-2021 19:40:10] THREAD 0 FINISHED SUCCESSFULLY.
[09-03-2021 21:21:04] FINISHED IMAGE GENERATION
[09-03-2021 21:21:04] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 667 Min 35 Sec
[09-03-2021 21:21:04] STEP 2: RUNNING INFERENCE
[09-03-2021 21:21:04] INFO: PREDICTION OUTPUT: 
[09-03-2021 21:21:04] INFO: DISTRIBUTED CPU SETUP.
[09-03-2021 21:21:04] INFO: TOTAL CALLERS: 28
[09-03-2021 21:21:04] INFO: THREADS PER CALLER: 1
[09-03-2021 21:21:04] INFO: MODEL LOADING TO ONNX
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (bad symbol table node signature)
ERROR: Can't determine (wrong B-tree signature)
ERROR: Caught KeyError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/dataloader_predict.py", line 51, in __getitem__
    image = hdf5_file['summaries'][image_name]['image'][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad local heap signature)'

**Comment by kishwarshafin** [comment]
@songbowang125 ,

Are you using `r0.5` or `r0.4`? I see your output has both versions mentioned:

Here you are running with `r0.5`:
```bash
The command is: docker run --ipc=host -v ... kishwars/pepper_deepvariant:r0.5 run_pepper_margin_deepvariant call_variant -b -f -o -p -t --ont.
```
But your output loads `r0.4`? 
```bash
And the logs before this error seems correct, which is :

Loaded image: kishwars/pepper_deepvariant:r0.4
```

**Comment by songbowang125** [comment]
I used r0.4 in my scripts and met this log and error.   I wrote the version wrong in the previous comment, sorry about that...

**Comment by kishwarshafin** [comment]
@songbowang125 , 

In that case my first suggestion would be to upgrade to `r0.5` and see if you still get the same error.

**Comment by songbowang125** [comment]
> @songbowang125 ,
> 
> In that case my first suggestion would be to upgrade to `r0.5` and see if you still get the same error.

ok, I'will try r0.5.

**Comment by songbowang125** [comment]
I re-run with r0.5 on my samples and met a new error.
The command is: docker run --ipc=host -v ....kishwars/pepper_deepvariant:r0.5 run_pepper_margin_deepvariant call_variant -b -f -o -p -t --ont.
And the error log:
Loaded image: kishwars/pepper_deepvariant:r0.5
Load finish
[09-08-2021 03:04:56] INFO: CALL VARIANT MODULE SELECTED
[09-08-2021 03:04:57] INFO: RUN-ID: 09082021_030457
[09-08-2021 03:04:57] INFO: IMAGE OUTPUT: 
[09-08-2021 03:04:57] INFO: STEP 1/3 GENERATING IMAGES:
[09-08-2021 03:04:57] INFO: COMMON CONTIGS FOUND: 
[09-08-2021 03:04:57] INFO: TOTAL CONTIGS: 224 TOTAL INTERVALS: 31097 TOTAL BASES: 3090147635
[09-08-2021 03:04:57] INFO: STARTING PROCESS: 0 FOR 1111 INTERVALS
[09-08-2021 03:05:17] INFO: [THREAD 00] 10/1111 COMPLETE (0%) [ELAPSED TIME: 0 Min 19 Sec]
[09-08-2021 04:09:49] INFO: [THREAD 00] 1110/1111 COMPLETE (99%) [ELAPSED TIME: 64 Min 51 Sec]
[09-08-2021 04:09:49] INFO: THREAD 0 FINISHED SUCCESSFULLY.
[09-08-2021 04:27:34] INFO: FINISHED IMAGE GENERATION
[09-08-2021 04:27:34] INFO: TOTAL ELAPSED TIME FOR GENERATING IMAGES: 82 Min 36 Sec
[09-08-2021 04:27:34] INFO: STEP 2/3 RUNNING INFERENCE
[09-08-2021 04:27:34] INFO: OUTPUT: 
[09-08-2021 04:27:34] INFO: DISTRIBUTED CPU SETUP.
[09-08-2021 04:27:34] INFO: TOTAL CALLERS: 28
[09-08-2021 04:27:34] INFO: THREADS PER CALLER: 1
[09-08-2021 04:27:35] INFO: MODEL LOADING TO ONNX
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending

**Comment by kishwarshafin** [comment]
@songbowang125 

The model failing is something I haven't seen before. What is the reference that you are using? Can you run it on a small contig on your data and see if that's still happening? If you fail to debug, will it be possible to share an example so I can debug this locally?

**Comment by kishwarshafin** [comment]
@songbowang125 

Closing this for inactivity. Please report back once it's convenient for you.
