### ISSUE TITLE
ONT var calling pipeline doesn't seem to stop on error

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/pepper#99]
Command

```bash
$ run_pepper_margin_deepvariant call_variant \
  -b BAM \
  -f FASTA \
  -t 16 \
  -s 6061-SL-0020 \
  -o OUT_DIR \
  -p T662828295_ONT.21_22_y.deepvariant_pepper \
  --gvcf --phased_output --ont
```

Judged from the log, it might be an out-of-memory error, but the pipeline probably should stop after the error first appears instead of moving onto the next stage.

Log

```
[09-09-2021 22:51:10] INFO: VARIANT CALLING MODULE SELECTED
[09-09-2021 22:51:10] INFO: [1/9] RUNNING THE FOLLOWING COMMAND
-------
mkdir -p /cromwell_root/pepper_output; 
mkdir -p /cromwell_root/pepper_output/logs; 
mkdir -p /cromwell_root/pepper_output/intermediate_files;
-------
[09-09-2021 22:51:10] INFO: [2/9] RUNNING THE FOLLOWING COMMAND
-------
time pepper_snp call_variant -b fixed.bam -f /cromwell_root/broad-dsde-methods-long-reads/resources/references/grch38_noalt/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa -t 16 -m /opt/pepper_models/PEPPER_SNP_R941_ONT_V4.pkl -o /cromwell_root/pepper_output/pepper_snp/ -s 6061-SL-0020 -w 4 -bs 64 --ont 2>&1 | tee /cromwell_root/pepper_output/logs/1_pepper_snp.log
-------
[09-09-2021 22:51:21] INFO: CALL VARIANT MODULE SELECTED.
[09-09-2021 22:51:21] INFO: ONT PROFILE SET FOR VARIANT CALLING.
[09-09-2021 22:51:21] INFO: RUN-ID: 09092021_225121
[09-09-2021 22:51:21] INFO: IMAGE OUTPUT: /cromwell_root/pepper_output/pepper_snp/images_09092021_225121/
[09-09-2021 22:51:21] STEP 1: GENERATING IMAGES
[09-09-2021 22:51:21] INFO: COMMON CONTIGS FOUND: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrM', 'chrX', 'chrY']
[09-09-2021 22:51:21] INFO: TOTAL CONTIGS: 25 TOTAL INTERVALS: 30895
[09-09-2021 22:51:21] STARTING THREAD: 0 FOR 1931 INTERVALS
[09-09-2021 22:51:21] INFO:  10/1931 COMPLETE (0%) [ELAPSED TIME: 0 Min 0 Sec]
[09-09-2021 22:51:21] INFO:  20/1931 COMPLETE (1%) [ELAPSED TIME: 0 Min 0 Sec]
...
[09-09-2021 23:15:16] INFO:  1920/1931 COMPLETE (99%) [ELAPSED TIME: 23 Min 54 Sec]
[09-09-2021 23:15:16] INFO:  1930/1931 COMPLETE (99%) [ELAPSED TIME: 23 Min 55 Sec]
[09-09-2021 23:15:17] THREAD 0 FINISHED SUCCESSFULLY.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.
[09-09-2021 23:22:47] FINISHED IMAGE GENERATION
[09-09-2021 23:22:47] TOTAL ELAPSED TIME FOR IMAGE GENERATION: 31 Min 25 Sec
[09-09-2021 23:22:47] STEP 2: RUNNING INFERENCE
[09-09-2021 23:22:47] INFO: PREDICTION OUTPUT: /cromwell_root/pepper_output/pepper_snp/predictions_09092021_225121/
[09-09-2021 23:22:47] INFO: DISTRIBUTED CPU SETUP.
[09-09-2021 23:22:47] INFO: TOTAL CALLERS: 16
[09-09-2021 23:22:47] INFO: THREADS PER CALLER: 1
[09-09-2021 23:22:50] INFO: MODEL LOADING TO ONNX
[09-09-2021 23:24:31] INFO: BATCHES PROCESSED 5/105.
[09-09-2021 23:24:55] INFO: BATCHES PROCESSED 10/105.
[09-09-2021 23:25:20] INFO: BATCHES PROCESSED 15/105.
[09-09-2021 23:25:44] INFO: BATCHES PROCESSED 20/105.
[09-09-2021 23:26:08] INFO: BATCHES PROCESSED 25/105.
[09-09-2021 23:26:34] INFO: BATCHES PROCESSED 30/105.
[09-09-2021 23:26:58] INFO: BATCHES PROCESSED 35/105.
[09-09-2021 23:27:26] INFO: BATCHES PROCESSED 40/105.
[09-09-2021 23:27:51] INFO: BATCHES PROCESSED 45/105.
[09-09-2021 23:28:16] INFO: BATCHES PROCESSED 50/105.
[09-09-2021 23:28:42] INFO: BATCHES PROCESSED 55/105.
[09-09-2021 23:29:08] INFO: BATCHES PROCESSED 60/105.
[09-09-2021 23:29:34] INFO: BATCHES PROCESSED 65/105.
[09-09-2021 23:29:59] INFO: BATCHES PROCESSED 70/105.
[09-09-2021 23:30:25] INFO: BATCHES PROCESSED 75/105.
[09-09-2021 23:30:47] INFO: BATCHES PROCESSED 80/105.
[09-09-2021 23:31:12] INFO: BATCHES PROCESSED 85/105.
[09-09-2021 23:31:38] INFO: BATCHES PROCESSED 90/105.
[09-09-2021 23:32:04] INFO: BATCHES PROCESSED 95/105.
[09-09-2021 23:32:26] INFO: BATCHES PROCESSED 100/105.
[09-09-2021 23:32:47] INFO: BATCHES PROCESSED 105/105.
ERROR: Unable to open file (bad object header version number)
ERROR: Unable to open file (bad object header version number)
[09-09-2021 23:32:47] INFO: THREAD 0 FINISHED SUCCESSFULLY.
[09-09-2021 23:33:11] INFO: FINISHED PREDICTION
[09-09-2021 23:33:11] INFO: ELAPSED TIME: 10 Min 21 Sec
[09-09-2021 23:33:11] INFO: PREDICTION FINISHED SUCCESSFULLY. 
[09-09-2021 23:33:11] TOTAL ELAPSED TIME FOR INFERENCE: 10 Min 23 Sec
[09-09-2021 23:33:11] STEP 3: RUNNING FIND CANDIDATES
[09-09-2021 23:33:11] INFO: PREDICTION OUTPUT: /cromwell_root/pepper_output/pepper_snp/
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 445, in main
    set_profile)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/CallVariant.py", line 126, in call_variant
    set_profile)
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/FindSNPCandidates.py", line 34, in snp_candidate_finder
    with h5py.File(prediction_file, 'r') as hdf5_file:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

real	42m6.521s
user	233m16.363s
sys	5m17.479s
[09-09-2021 23:33:17] INFO: [3/9] RUNNING THE FOLLOWING COMMAND
-------
mv /cromwell_root/pepper_output/pepper_snp/*.vcf /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf; 
bgzip /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf; 
tabix -p vcf /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz; 
rm -rf /cromwell_root/pepper_output/pepper_snp/; 
echo "CONTIGS FOUND IN PEPPER SNP VCF:"; 
zcat /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz | grep -v '#' | cut -f1 | uniq
-------
mv: cannot stat '/cromwell_root/pepper_output/pepper_snp/*.vcf': No such file or directory
[bgzip] No such file or directory: /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf
tbx_index_build failed: /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz
CONTIGS FOUND IN PEPPER SNP VCF:
gzip: /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz: No such file or directory
[09-09-2021 23:33:20] INFO: [4/9] RUNNING THE FOLLOWING COMMAND
-------
time margin phase fixed.bam /cromwell_root/broad-dsde-methods-long-reads/resources/references/grch38_noalt/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 16 -V -o /cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee /cromwell_root/pepper_output/logs/2_margin_haplotag.log;
mv /cromwell_root/pepper_output/*.bam /cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam; 
samtools index -@16 /cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam
-------
Could not read from vcf file: /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz


real	0m0.253s
user	0m0.002s
sys	0m0.006s
mv: cannot stat '/cromwell_root/pepper_output/*.bam': No such file or directory
[E::hts_open_format] Failed to open file "/cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam" : No such file or directory
samtools index: failed to open "/cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam": No such file or directory
[09-09-2021 23:33:21] ERROR: None]
Traceback (most recent call last):
  File "/usr/local/bin/run_pepper_margin_deepvariant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 732, in main
    run_variant_calling(flags)
  File "/usr/local/lib/python3.6/dist-packages/run_pepper_margin_deepvariant/run_pepper_margin_deepvariant.py", line 376, in run_variant_calling
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time margin phase fixed.bam /cromwell_root/broad-dsde-methods-long-reads/resources/references/grch38_noalt/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa /cromwell_root/pepper_output/PEPPER_SNP_OUPUT.vcf.gz /opt/margin_dir/params/misc/allParams.ont_haplotag.json -t 16 -V -o /cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN 2>&1 | tee /cromwell_root/pepper_output/logs/2_margin_haplotag.log;
mv /cromwell_root/pepper_output/*.bam /cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam; 
samtools index -@16 /cromwell_root/pepper_output/MARGIN_PHASED.PEPPER_SNP_MARGIN.haplotagged.bam' returned non-zero exit status 1.
```

Thanks!

**Comment by kishwarshafin** [comment]
@SHuang-Broad , which version is this? Are you at liberty to share the data so I can debug this issue?

**Comment by SHuang-Broad** [comment]
Version is 4.1, running inside a docker container.

Unfortunately, this particular sample isn't sharable at the moment (it will be, but I don't know when).

I'll try to reproduce this error (intentionally allocate a small memory) on an actual public data and share the script with you.

Oh I forgot to mention, this is on a machine without GPU.
That could be relevant information, sorry I forgot to include that before.

**Comment by kishwarshafin** [comment]
Sound good, I'll close this issue. We are very actively working to change the pipeline, we are not at a stage where we can engineer the main interface as it changes very often. Once we reach a good solution, I'll make sure to improve the main script that wraps the submodules.
